// ==UserScript==
// @name           [AI Studio] 快捷键跳转 [20260522] v1.0.0
// @name:en        [AI Studio] Shortcut Jump [20260522] v1.0.0
// @namespace      https://github.com/0-V-linuxdo/Template_shortcuts.js
// @description    为 Google AI Studio Playground 提供基础快捷键：左侧/右侧边栏展开折叠，以及底部 Tools 工具栏中的 Google Search、Code execution、URL context 开关。
// @description:en Basic shortcuts for Google AI Studio Playground: left/right sidebar toggles plus bottom Tools toolbar switches for Google Search, Code execution, and URL context.

// @version        [20260522] v1.0.0
// @update-log     1.0.0: 新增 AI Studio 基础快捷键脚本，覆盖左/右侧边栏展开折叠与底部 Tools 工具栏 Google Search、Code execution、URL context 开关。
// @update-log:en  1.0.0: Added the AI Studio shortcut script with left/right side-panel toggles and bottom Tools switches for Google Search, Code execution, and URL context.

// @match          https://aistudio.google.com/*

// @grant          GM_registerMenuCommand
// @grant          GM_unregisterMenuCommand
// @grant          GM_getValue
// @grant          GM_setValue
// @grant          GM_xmlhttpRequest

// @connect        *

// @icon           data:image/svg+xml,%3Csvg%20viewBox%3D%220%200%2064%2064%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20aria-hidden%3D%22true%22%20role%3D%22img%22%20preserveAspectRatio%3D%22xMidYMid%20meet%22%20class%3D%22aistudio-keycap-icon%22%3E%20%3Cstyle%3E%20%3Aroot%20%7B%20color-scheme%3A%20light%20dark%3B%20%7D%20.aistudio-keycap-icon%20%7B%20color%3A%20%23000000%3B%20%7D%20%40media%20(prefers-color-scheme%3A%20dark)%20%7B%20.aistudio-keycap-icon%20%7B%20color%3A%20%23FFFFFF%3B%20%7D%20%7D%20%3C%2Fstyle%3E%20%3Cpath%20d%3D%22M52%202H12C6.478%202%202%206.477%202%2011.999V52c0%205.522%204.478%2010%2010%2010h40c5.522%200%2010-4.478%2010-10V11.999C62%206.477%2057.522%202%2052%202zm5%2043.666A8.333%208.333%200%200%201%2048.667%2054H15.333A8.333%208.333%200%200%201%207%2045.666V12.333A8.332%208.332%200%200%201%2015.333%204h33.334A8.332%208.332%200%200%201%2057%2012.333v33.333z%22%20fill%3D%22currentColor%22%20fill-rule%3D%22evenodd%22%20clip-rule%3D%22evenodd%22%3E%3C%2Fpath%3E%20%3Cg%20transform%3D%22translate(12%2011)%22%20fill%3D%22none%22%20stroke%3D%22currentColor%22%20stroke-width%3D%222.35%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%3E%3Cpath%20d%3D%22M11%207.5%2014.5%204%2018%207.5%2014.5%2011z%22%3E%3C%2Fpath%3E%3Cpath%20d%3D%22M27%207.5%2030.5%204%2034%207.5%2030.5%2011z%22%3E%3C%2Fpath%3E%3Cpath%20d%3D%22M19%2030.5%2022.5%2027%2026%2030.5%2022.5%2034z%22%3E%3C%2Fpath%3E%3Cpath%20d%3D%22M13%2020h19%22%3E%3C%2Fpath%3E%3Cpath%20d%3D%22M22.5%2012v19%22%3E%3C%2Fpath%3E%3Cpath%20d%3D%22M16%2016.5%2029%2029.5%22%3E%3C%2Fpath%3E%3Cpath%20d%3D%22M29%2016.5%2016%2029.5%22%3E%3C%2Fpath%3E%3C%2Fg%3E%20%3C%2Fsvg%3E
// @require        https://github.com/0-V-linuxdo/Template_shortcuts.js/raw/refs/heads/release/Template_JS/%5BTemplate%5D%20shortcut%20core.js?v=20260519.1.0.0
// ==/UserScript==

/* ===================== IMPORTANT · NOTICE · START =====================
 *
 * 1. [编辑指引 | Edit Guidance]
 *    • ⚠️ 这是一个自动生成的文件：请不要直接修改当前产物。
 *    • ⚠️ 源码真源位于当前仓库 `main` 分支的 `src/modules/` 与 `src/sites/`；站点元数据位于 `src/sites/manifest.js`；Template 头部元数据位于 `src/userscript/header.txt`。
 *    • ⚠️ 在 `main` 分支运行 `npm run build` 会刷新本地 `Template_JS/` 与 `Site_JS/`。
 *    • ⚠️ 最新发布物应同步到当前仓库的 `release` 分支；release userscript 通过 `@require` 加载 `Template_JS/[Template] shortcut core.js`；`archive/` 仅保存历史归档与参考资料，不参与当前运行时加载。
 *    • ⚠️ This is a generated artifact. Do not edit this file directly. The source of truth lives in the current repository's `main` branch under `src/modules/`, `src/sites/`, `src/sites/manifest.js`, and `src/userscript/header.txt`. Run `npm run build` on `main` to refresh local `Template_JS/` and `Site_JS/` outputs, then stage release assets for the repository's `release` branch.
 *
 * ----------------------------------------------------------------------
 *
 * 2. [安全提示 | Safety Reminder]
 *    • ✅ 必须使用 `setTrustedHTML`，不得使用 `innerHTML`。
 *    • ✅ Always call `setTrustedHTML`; never rely on `innerHTML`.
 *
 * ====================== IMPORTANT · NOTICE · END ======================
 */

(() => {
  // src/sites/aistudio/index.js
  (function() {
    "use strict";
    const ShortcutTemplate = window.ShortcutTemplate;
    if (!ShortcutTemplate || typeof ShortcutTemplate.createShortcutEngine !== "function") {
      console.error("[AI Studio Shortcut] Template module not found.");
      return;
    }
    const LOG_TAG = "[AI Studio Shortcut Script]";
    const TemplateUtils = ShortcutTemplate.utils || {};
    const DomUtils = TemplateUtils.dom || {};
    const EventUtils = TemplateUtils.events || {};
    const safeQuerySelectorAll = typeof DomUtils.safeQuerySelectorAll === "function" ? DomUtils.safeQuerySelectorAll : (root, selector) => {
      const base = root && typeof root.querySelectorAll === "function" ? root : document;
      try {
        return Array.from(base.querySelectorAll(selector));
      } catch {
        return [];
      }
    };
    const isVisible = typeof DomUtils.isVisible === "function" ? DomUtils.isVisible : (element) => {
      if (!element || element.hidden) return false;
      try {
        return !!(element.offsetWidth || element.offsetHeight || element.getClientRects().length);
      } catch {
        return false;
      }
    };
    const sleep = typeof TemplateUtils.sleep === "function" ? TemplateUtils.sleep : (ms) => new Promise((resolve) => setTimeout(resolve, ms));
    const defaultIconURL = "https://aistudio.google.com/favicon.ico";
    const SITE_MESSAGES = Object.freeze({
      "zh-CN": {
        menuCommandLabel: "AI Studio - 设置快捷键",
        panelTitle: "AI Studio - 自定义快捷键",
        shortcuts: {
          toggleLeftSidebar: "左侧边栏展开/折叠",
          toggleRightSidebar: "右侧边栏展开/折叠",
          toolGoogleSearch: "工具：Google 搜索",
          toolCodeExecution: "工具：代码执行",
          toolUrlContext: "工具：URL 上下文"
        },
        dataAdapters: {
          toolSwitch: {
            label: "工具名称关键词（或粘贴 JSON，高级用法）:",
            placeholder: "例如: Grounding with Google Search / Code execution / URL context"
          }
        }
      },
      "en-US": {
        menuCommandLabel: "AI Studio - Shortcut settings",
        panelTitle: "AI Studio - Custom shortcuts",
        shortcuts: {
          toggleLeftSidebar: "Toggle left sidebar",
          toggleRightSidebar: "Toggle right sidebar",
          toolGoogleSearch: "Tool: Google Search",
          toolCodeExecution: "Tool: Code execution",
          toolUrlContext: "Tool: URL context"
        },
        dataAdapters: {
          toolSwitch: {
            label: "Tool keyword (or paste JSON, advanced):",
            placeholder: "Example: Grounding with Google Search / Code execution / URL context"
          }
        }
      }
    });
    const siteText = (key, fallback) => ({ ctx } = {}) => ctx?.i18n?.t?.(key, {}, fallback) || fallback;
    function createSvgIconDataUrl(body, { color = "#202124" } = {}) {
      const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="${color}" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round">${body}</svg>`;
      return `data:image/svg+xml,${encodeURIComponent(svg)}`;
    }
    function createShortcutIconSet(body) {
      return Object.freeze({
        icon: createSvgIconDataUrl(body, { color: "#202124" }),
        iconDark: createSvgIconDataUrl(body, { color: "#F8FAFC" }),
        iconAdaptive: false
      });
    }
    const SHORTCUT_ICON_SETS = Object.freeze({
      leftSidebar: createShortcutIconSet('<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M9 4v16"/><path d="M6.5 9h.01"/><path d="M6.5 12h.01"/><path d="M6.5 15h.01"/>'),
      rightSidebar: createShortcutIconSet('<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M15 4v16"/><path d="M18 9h.01"/><path d="M18 12h.01"/><path d="M18 15h.01"/>'),
      search: createShortcutIconSet('<circle cx="11" cy="11" r="6"/><path d="m20 20-4.2-4.2"/><path d="M5 11h12"/><path d="M11 5a10 10 0 0 1 0 12"/><path d="M11 5a10 10 0 0 0 0 12"/>'),
      code: createShortcutIconSet('<path d="m9 18-6-6 6-6"/><path d="m15 6 6 6-6 6"/><path d="m14 4-4 16"/>'),
      urlContext: createShortcutIconSet('<path d="M10 13a5 5 0 0 0 7.1 0l2-2a5 5 0 0 0-7.1-7.1l-1.1 1.1"/><path d="M14 11a5 5 0 0 0-7.1 0l-2 2a5 5 0 0 0 7.1 7.1l1.1-1.1"/>')
    });
    const defaultIcons = [
      { name: "AI Studio", url: defaultIconURL },
      { name: "Google", url: "https://www.google.com/favicon.ico" },
      { name: "Gemini", url: "https://www.gstatic.com/lamda/images/gemini_sparkle_v002_d4735304ff6292a690345.svg" },
      { name: "ChatGPT", url: "https://chatgpt.com/favicon.ico" },
      { name: "Claude", url: "https://claude.ai/favicon.ico" },
      { name: "Perplexity", url: "https://www.perplexity.ai/favicon.ico" },
      { name: "GitHub", url: "https://github.githubassets.com/favicons/favicon.svg" },
      { name: "YouTube", url: "https://www.youtube.com/favicon.ico" }
    ];
    const protectedIconUrls = [defaultIconURL];
    const baseShortcut = {
      url: "",
      urlMethod: "current",
      urlAdvanced: "href",
      selector: "",
      simulateKeys: "",
      customAction: "",
      data: {},
      icon: defaultIconURL
    };
    function createShortcut(overrides, iconKey = "") {
      const iconSet = SHORTCUT_ICON_SETS[String(iconKey || "")] || {};
      return { ...baseShortcut, ...iconSet, ...overrides || {} };
    }
    const defaultShortcuts = [
      createShortcut({
        key: "aistudio.toggleLeftSidebar",
        name: "Toggle Left Sidebar",
        labelKey: "shortcuts.toggleLeftSidebar",
        actionType: "custom",
        customAction: "toggleLeftSidebar",
        hotkey: "CTRL+B"
      }, "leftSidebar"),
      createShortcut({
        key: "aistudio.toggleRightSidebar",
        name: "Toggle Right Sidebar",
        labelKey: "shortcuts.toggleRightSidebar",
        actionType: "custom",
        customAction: "toggleRightSidebar",
        hotkey: "CTRL+SHIFT+B"
      }, "rightSidebar"),
      createShortcut({
        key: "aistudio.toolGoogleSearch",
        name: "Toggle Tool: Grounding with Google Search",
        labelKey: "shortcuts.toolGoogleSearch",
        actionType: "custom",
        customAction: "toolSwitch",
        hotkey: "CTRL+SHIFT+G",
        data: { tool: { keyword: "Grounding with Google Search", aliases: ["Google Search", "Search"] } }
      }, "search"),
      createShortcut({
        key: "aistudio.toolCodeExecution",
        name: "Toggle Tool: Code execution",
        labelKey: "shortcuts.toolCodeExecution",
        actionType: "custom",
        customAction: "toolSwitch",
        hotkey: "CTRL+SHIFT+C",
        data: { tool: { keyword: "Code execution", aliases: ["Code execution", "Code"] } }
      }, "code"),
      createShortcut({
        key: "aistudio.toolUrlContext",
        name: "Toggle Tool: URL context",
        labelKey: "shortcuts.toolUrlContext",
        actionType: "custom",
        customAction: "toolSwitch",
        hotkey: "CTRL+SHIFT+U",
        data: { tool: { keyword: "URL context", aliases: ["URL context", "URL"] } }
      }, "urlContext")
    ];
    function normalizeText(text) {
      return String(text || "").replace(/\s+/g, " ").trim().toLowerCase();
    }
    function getElementText(element) {
      if (!element) return "";
      const parts = [];
      for (const attr of ["aria-label", "title", "data-tooltip", "data-test-id", "placeholder"]) {
        const value = element.getAttribute?.(attr);
        if (value) parts.push(value);
      }
      if ("value" in element && element.value) parts.push(element.value);
      if (element.textContent) parts.push(element.textContent);
      return parts.join(" ");
    }
    function textMatchesAny(element, matchers) {
      const text = normalizeText(getElementText(element));
      if (!text) return false;
      const list = Array.isArray(matchers) ? matchers : [matchers];
      return list.some((matcher) => {
        if (matcher == null) return false;
        if (matcher instanceof RegExp) {
          try {
            return matcher.test(getElementText(element));
          } catch {
            return false;
          }
        }
        const target = normalizeText(matcher);
        return target ? text.includes(target) : false;
      });
    }
    function isDisabled(element) {
      if (!element) return true;
      if (element.disabled) return true;
      if (element.getAttribute?.("aria-disabled") === "true") return true;
      const disabledParent = element.closest?.('button[disabled], [aria-disabled="true"]');
      return !!disabledParent;
    }
    function getClickableElement(element) {
      if (!element) return null;
      return element.closest?.('button, a, [role="button"], [role="menuitem"], mat-chip, mat-chip-option, [onclick], [tabindex]') || element;
    }
    function clickElement(element) {
      const target = getClickableElement(element);
      if (!target || isDisabled(target)) return false;
      if (typeof EventUtils.simulateClick === "function") {
        try {
          if (EventUtils.simulateClick(target, { nativeFallback: true })) return true;
        } catch {
        }
      }
      try {
        if (typeof target.click === "function") {
          target.click();
          return true;
        }
      } catch {
      }
      try {
        target.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true, view: window }));
        return true;
      } catch {
        return false;
      }
    }
    function clickPoint(x, y) {
      let target = null;
      try {
        target = document.elementFromPoint(x, y);
      } catch {
        target = null;
      }
      return target ? clickElement(target) : false;
    }
    function getVisibleInteractiveElements(root = document) {
      const selectors = [
        "button",
        "a",
        '[role="button"]',
        '[role="menuitem"]',
        "mat-chip",
        "mat-chip-option",
        ".mat-mdc-chip",
        "[tabindex]"
      ];
      const elements = [];
      const seen = /* @__PURE__ */ new Set();
      for (const selector of selectors) {
        for (const element of safeQuerySelectorAll(root, selector)) {
          if (!element || seen.has(element) || !isVisible(element) || isDisabled(element)) continue;
          seen.add(element);
          elements.push(element);
        }
      }
      return elements;
    }
    function findFirstInteractiveByText(matchers, {
      root = document,
      minTop = null,
      maxTop = null,
      minLeft = null,
      maxRight = null,
      preferBottom = false
    } = {}) {
      const candidates = getVisibleInteractiveElements(root).filter((element) => {
        if (!textMatchesAny(element, matchers)) return false;
        try {
          const rect = element.getBoundingClientRect();
          if (minTop != null && rect.top < minTop) return false;
          if (maxTop != null && rect.top > maxTop) return false;
          if (minLeft != null && rect.left < minLeft) return false;
          if (maxRight != null && rect.right > maxRight) return false;
        } catch {
          return false;
        }
        return true;
      });
      if (preferBottom) {
        candidates.sort((a, b) => b.getBoundingClientRect().top - a.getBoundingClientRect().top);
      }
      return candidates[0] || null;
    }
    function scoreIconTextForSidebar(element, tokens) {
      const text = normalizeText(getElementText(element));
      let score = 0;
      for (const token of tokens) {
        if (text.includes(token)) score += 4;
      }
      if (/\bmenu\b|side\s*nav|sidebar|panel/.test(text)) score += 3;
      return score;
    }
    function findTopEdgeButton({ side }) {
      const viewportWidth = Math.max(document.documentElement?.clientWidth || 0, window.innerWidth || 0);
      const candidates = getVisibleInteractiveElements(document).filter((element) => {
        try {
          const rect = element.getBoundingClientRect();
          if (rect.top > 92 || rect.bottom < 0) return false;
          if (rect.width > 96 || rect.height > 72) return false;
          if (side === "left") return rect.left < Math.max(280, viewportWidth * 0.24);
          return rect.right > viewportWidth - 120;
        } catch {
          return false;
        }
      });
      const tokens = side === "left" ? ["menu", "navigation", "sidebar", "side nav", "left panel"] : ["tune", "settings", "right panel", "run settings", "sidebar"];
      candidates.sort((a, b) => {
        const rectA = a.getBoundingClientRect();
        const rectB = b.getBoundingClientRect();
        const scoreA = scoreIconTextForSidebar(a, tokens);
        const scoreB = scoreIconTextForSidebar(b, tokens);
        if (scoreA !== scoreB) return scoreB - scoreA;
        if (side === "left") return rectA.left - rectB.left;
        return rectB.right - rectA.right;
      });
      return candidates[0] || null;
    }
    function toggleLeftSidebar() {
      const direct = findFirstInteractiveByText([
        /toggle.*(?:navigation|sidebar|side nav|menu)/i,
        /(?:navigation|sidebar|side nav|menu).*(?:toggle|collapse|expand)/i,
        "menu"
      ], { maxTop: 120 });
      const target = direct || findTopEdgeButton({ side: "left" });
      if (!clickElement(target)) {
        console.warn(`${LOG_TAG} left sidebar toggle button not found.`);
      }
    }
    function toggleRightSidebar() {
      const direct = findFirstInteractiveByText([
        /(?:run settings|right panel|settings|sidebar).*(?:toggle|collapse|expand)/i,
        /toggle.*(?:run settings|right panel|settings|sidebar)/i,
        "tune"
      ], { maxTop: 120 });
      const target = direct || findTopEdgeButton({ side: "right" });
      if (!clickElement(target)) {
        console.warn(`${LOG_TAG} right sidebar toggle button not found.`);
      }
    }
    function resolveToolTarget(data) {
      const raw = data && typeof data === "object" && !Array.isArray(data) ? data : {};
      const tool = raw.tool ?? raw.menu ?? raw.keyword ?? raw.textMatch ?? raw;
      if (typeof tool === "string") {
        const keyword = tool.trim();
        return { keyword, aliases: keyword ? [keyword] : [] };
      }
      if (tool && typeof tool === "object" && !Array.isArray(tool)) {
        const keyword = String(tool.keyword || tool.name || tool.id || tool.textMatch || "").trim();
        const aliases = Array.isArray(tool.aliases) ? tool.aliases.map((value) => String(value || "").trim()).filter(Boolean) : [];
        const list = [keyword, ...aliases].filter(Boolean);
        return { keyword: keyword || list[0] || "", aliases: list };
      }
      return { keyword: "", aliases: [] };
    }
    function getToolMatchers(target) {
      const aliases = Array.isArray(target?.aliases) ? target.aliases : [];
      const keyword = String(target?.keyword || "").trim();
      return Array.from(new Set([keyword, ...aliases].map((value) => String(value || "").trim()).filter(Boolean)));
    }
    function findToolsButton() {
      const minTop = Math.max(0, (window.innerHeight || 0) * 0.45);
      return findFirstInteractiveByText(["Tools", "工具"], { minTop, preferBottom: true }) || findFirstInteractiveByText([/tools/i, /工具/], { preferBottom: true });
    }
    function isInBottomPromptToolbar(element) {
      if (!element) return false;
      try {
        const rect = element.getBoundingClientRect();
        const viewportHeight = Math.max(document.documentElement?.clientHeight || 0, window.innerHeight || 0);
        return rect.top > viewportHeight * 0.52;
      } catch {
        return false;
      }
    }
    function findActiveToolChip(target) {
      const matchers = getToolMatchers(target);
      if (matchers.length === 0) return null;
      const candidates = [
        "mat-chip",
        "mat-chip-option",
        ".mat-mdc-chip",
        '[class*="chip"]',
        "button",
        '[role="button"]'
      ];
      for (const selector of candidates) {
        const matches = safeQuerySelectorAll(document, selector).filter((element) => isVisible(element) && isInBottomPromptToolbar(element) && textMatchesAny(element, matchers));
        if (matches.length > 0) {
          matches.sort((a, b) => b.getBoundingClientRect().top - a.getBoundingClientRect().top);
          return matches[0];
        }
      }
      return null;
    }
    function closeActiveToolChip(chip) {
      if (!chip) return false;
      const closeButton = findFirstInteractiveByText([
        /^(close|remove|dismiss|cancel)$/i,
        /(?:close|remove|dismiss|cancel|移除|关闭|删除)/i,
        "×",
        "x"
      ], { root: chip });
      if (clickElement(closeButton)) return true;
      try {
        const rect = chip.getBoundingClientRect();
        if (rect.width > 0 && rect.height > 0) {
          if (clickPoint(rect.right - Math.min(18, Math.max(8, rect.width * 0.16)), rect.top + rect.height / 2)) {
            return true;
          }
        }
      } catch {
      }
      return clickElement(chip);
    }
    function findToolMenuItem(target) {
      const matchers = getToolMatchers(target);
      if (matchers.length === 0) return null;
      const overlaySelectors = [
        '[role="menu"]',
        '[role="listbox"]',
        ".cdk-overlay-pane",
        ".mat-mdc-menu-panel",
        ".mat-mdc-select-panel",
        '[class*="overlay"]'
      ];
      const roots = [document];
      for (const selector of overlaySelectors) {
        roots.push(...safeQuerySelectorAll(document, selector).filter(isVisible));
      }
      for (const root of roots) {
        const item = findFirstInteractiveByText(matchers, { root });
        if (item && !isInBottomPromptToolbar(item)) return item;
      }
      return null;
    }
    async function openToolsMenu() {
      const toolsButton = findToolsButton();
      if (!toolsButton) return false;
      if (!clickElement(toolsButton)) return false;
      await sleep(180);
      return true;
    }
    async function toggleToolSwitch({ shortcut } = {}) {
      const target = resolveToolTarget(shortcut?.data || {});
      if (!target.keyword) {
        console.warn(`${LOG_TAG} toolSwitch shortcut has no tool keyword.`);
        return;
      }
      const activeChip = findActiveToolChip(target);
      if (activeChip) {
        if (!closeActiveToolChip(activeChip)) {
          console.warn(`${LOG_TAG} failed to close active tool chip: ${target.keyword}`);
        }
        return;
      }
      let menuItem = findToolMenuItem(target);
      if (!menuItem) {
        await openToolsMenu();
        menuItem = findToolMenuItem(target);
      }
      if (!clickElement(menuItem)) {
        console.warn(`${LOG_TAG} tool menu item not found: ${target.keyword}`);
      }
    }
    function formatToolSwitchData(data) {
      const target = resolveToolTarget(data);
      if (target.keyword) return target.keyword;
      try {
        return JSON.stringify(data || {}, null, 2);
      } catch {
        return "";
      }
    }
    function parseToolSwitchData(text) {
      const trimmed = String(text ?? "").trim();
      if (!trimmed) return {};
      if (trimmed.startsWith("{") || trimmed.startsWith("[")) {
        const parsed = JSON.parse(trimmed);
        if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error("data must be an object");
        return parsed;
      }
      return { tool: { keyword: trimmed } };
    }
    const engine = ShortcutTemplate.createShortcutEngine({
      menuCommandLabel: "AI Studio - 设置快捷键",
      panelTitle: "AI Studio - 自定义快捷键",
      storageKeys: {
        shortcuts: "aistudio_shortcuts_v1",
        iconCachePrefix: "aistudio_icon_cache_v1::",
        userIcons: "aistudio_user_icons_v1"
      },
      ui: {
        idPrefix: "aistudio",
        cssPrefix: "aistudio",
        compactBreakpoint: 800
      },
      i18n: {
        messages: SITE_MESSAGES
      },
      defaultIconURL,
      iconLibrary: defaultIcons,
      protectedIconUrls,
      defaultShortcuts,
      customActions: {
        toggleLeftSidebar,
        toggleRightSidebar,
        toolSwitch: toggleToolSwitch
      },
      customActionDataAdapters: {
        toolSwitch: {
          label: siteText("dataAdapters.toolSwitch.label", "Tool keyword (or paste JSON, advanced):"),
          placeholder: siteText("dataAdapters.toolSwitch.placeholder", "Example: Grounding with Google Search / Code execution / URL context"),
          format: formatToolSwitchData,
          parse: parseToolSwitchData
        }
      },
      consoleTag: LOG_TAG,
      colors: {
        primary: "#4285F4"
      },
      shouldBypassIconCache: (url) => {
        return url && url.startsWith("https://aistudio.google.com/");
      }
    });
    engine.init();
  })();
})();
