// ==UserScript==
// @name         [ChatGPT] 快捷键跳转 [20260423] v1.0.0
// @namespace    https://github.com/0-V-linuxdo/Template_shortcuts.js
// @description  为 ChatGPT 提供可视化自定义快捷键：支持 URL/按钮/按键动作、工具菜单（Web/Canvas/Thinking/Deep research/Create image）一键触发，以及快捷输入（文本+图片、循环发送、自动新建对话）。

// @version      [20260423] v1.0.0
// @update-log   1.0.0: 修正站点脚本 @resource 地址，统一改为 release 分支 raw ESM 资源，避免继续引用本地相对路径。

// @match        https://chatgpt.com/*

// @grant        GM_registerMenuCommand
// @grant        GM_getValue
// @grant        GM_setValue
// @grant        GM_xmlhttpRequest
// @grant        GM_getResourceURL

// @connect      *

// @icon         https://github.com/0-V-linuxdo/Template_shortcuts.js/raw/refs/heads/release/Site_Icon/ChatGPT_keycap.svg
// @resource     template-core https://github.com/0-V-linuxdo/Template_shortcuts.js/raw/refs/heads/release/dist/esm/template-core.js
// @resource     site-entry https://github.com/0-V-linuxdo/Template_shortcuts.js/raw/refs/heads/release/dist/esm/sites/chatgpt.js
// ==/UserScript==

/* ===================== IMPORTANT · NOTICE · START =====================
 *
 * 1. [编辑指引 | Edit Guidance]
 *    • ⚠️ 这是一个自动生成的文件：请不要直接修改当前产物。
 *    • ⚠️ 源码真源位于当前仓库 `main` 分支的 `src/modules/` 与 `src/sites/`；userscript bootstrap 模板位于 `src/userscript/entry.js`；站点元数据位于 `src/sites/manifest.js`；Template 归档头部元数据位于 `src/userscript/header.txt`。
 *    • ⚠️ 在 `main` 分支运行 `npm run build` 会刷新本地 `dist/esm/`、`Site_JS/` 与 `archive/Template_JS/[Template] shortcut core.js`。
 *    • ⚠️ 最新发布物应同步到当前仓库的 `release` 分支；`archive/` 仅保存历史归档与参考资料，不参与当前 userscript 运行时加载。
 *    • ⚠️ This is a generated artifact. Do not edit this file directly. The source of truth lives in the current repository's `main` branch under `src/modules/`, `src/sites/`, `src/userscript/entry.js`, `src/sites/manifest.js`, and `src/userscript/header.txt`. Run `npm run build` on `main` to refresh local outputs, then stage release assets for the repository's `release` branch.
 *
 * ----------------------------------------------------------------------
 *
 * 2. [安全提示 | Safety Reminder]
 *    • ✅ 必须使用 `setTrustedHTML`，不得使用 `innerHTML`。
 *    • ✅ Always call `setTrustedHTML`; never rely on `innerHTML`.
 *
 * ====================== IMPORTANT · NOTICE · END ======================
 */

(() => {
    'use strict';

    const SITE_ID = "chatgpt";
    const SITE_LABEL = "[ChatGPT] 快捷键跳转";
    const RESOURCE_NAMES = Object.freeze({
    "core": "template-core",
    "site": "site-entry"
});
    const BOOTSTRAP_MENU_COMMANDS = Object.freeze([]);
    const MENU_MESSAGE_SOURCE = "template-shortcuts-userscript";
    const MENU_PENDING_STORAGE_KEY = "__templateShortcutsMenuPending::chatgpt";
    const MENU_READY_STORAGE_KEY = "__templateShortcutsMenuReady::chatgpt";
    const MENU_PAGE_TOKEN = Date.now().toString(36) + '_' + Math.random().toString(36).slice(2, 10);

    function getGlobalScope() {
        return typeof globalThis !== 'undefined' ? globalThis : null;
    }

    function getSessionStorageSafe() {
        const scope = getGlobalScope();
        try {
            return scope?.sessionStorage || null;
        } catch {
            return null;
        }
    }

    function getDirectUserscriptApi(name) {
        switch (String(name || "")) {
            case 'GM_getValue':
                return typeof GM_getValue === 'function' ? GM_getValue : null;
            case 'GM_setValue':
                return typeof GM_setValue === 'function' ? GM_setValue : null;
            case 'GM_xmlhttpRequest':
                return typeof GM_xmlhttpRequest === 'function' ? GM_xmlhttpRequest : null;
            case 'GM_getResourceURL':
                return typeof GM_getResourceURL === 'function' ? GM_getResourceURL : null;
            case 'GM_registerMenuCommand':
                return typeof GM_registerMenuCommand === 'function' ? GM_registerMenuCommand : null;
            case 'GM_unregisterMenuCommand':
                return typeof GM_unregisterMenuCommand === 'function' ? GM_unregisterMenuCommand : null;
            default:
                return null;
        }
    }

    function getUserscriptApi(name) {
        const directBinding = getDirectUserscriptApi(name);
        if (typeof directBinding === 'function') return directBinding;

        const scope = getGlobalScope();
        if (!scope) return null;

        const direct = scope[name];
        if (typeof direct === 'function') return direct.bind(scope);

        const gm = scope.GM;
        if (gm && typeof gm === 'object') {
            const altName = name.replace(/^GM_/, '');
            const directGm = gm[altName];
            if (typeof directGm === 'function') return directGm.bind(gm);

            const lowerCamel = altName.charAt(0).toLowerCase() + altName.slice(1);
            const camelGm = gm[lowerCamel];
            if (typeof camelGm === 'function') return camelGm.bind(gm);
        }

        return null;
    }

    function exposeUserscriptApiResolver() {
        const scope = getGlobalScope();
        if (!scope) return;

        try {
            Object.defineProperty(scope, "__TEMPLATE_SHORTCUTS_GET_USERSCRIPT_API__", {
                value: getUserscriptApi,
                configurable: true,
                enumerable: false,
                writable: true
            });
            return;
        } catch {}

        try {
            scope["__TEMPLATE_SHORTCUTS_GET_USERSCRIPT_API__"] = getUserscriptApi;
        } catch {}
    }

    function createMenuBridge() {
        const register = getUserscriptApi('GM_registerMenuCommand');
        const unregister = getUserscriptApi('GM_unregisterMenuCommand');
        let settingsHandler = null;
        const commands = new Map();
        const scope = getGlobalScope();
        const dispatchTarget = scope?.document && typeof scope.document.dispatchEvent === 'function'
            ? scope.document
            : (scope && typeof scope.dispatchEvent === 'function' ? scope : null);

        function normalizeCommandKey(commandKey) {
            return String(commandKey || "").trim();
        }

        function createCommandId(commandKey) {
            const key = normalizeCommandKey(commandKey) || 'menu';
            return key + ':' + Date.now().toString(36) + ':' + Math.random().toString(36).slice(2, 10);
        }

        function readPendingEntries() {
            const storage = getSessionStorageSafe();
            if (!storage) return [];
            try {
                const raw = storage.getItem(MENU_PENDING_STORAGE_KEY);
                if (!raw) return [];
                const parsed = JSON.parse(raw);
                if (!Array.isArray(parsed)) return [];
                return parsed
                    .map((entry) => {
                        const id = typeof entry?.id === 'string' ? entry.id.trim() : '';
                        const key = normalizeCommandKey(entry?.key);
                        if (!id || !key) return null;
                        return Object.freeze({ id, key });
                    })
                    .filter(Boolean);
            } catch {
                return [];
            }
        }

        function writePendingEntries(entries) {
            const storage = getSessionStorageSafe();
            if (!storage) return;
            try {
                if (!Array.isArray(entries) || entries.length === 0) {
                    storage.removeItem(MENU_PENDING_STORAGE_KEY);
                    return;
                }
                storage.setItem(MENU_PENDING_STORAGE_KEY, JSON.stringify(entries));
            } catch {}
        }

        function isCurrentPageMenuReady() {
            const storage = getSessionStorageSafe();
            if (!storage || !MENU_PAGE_TOKEN) return false;
            try {
                return String(storage.getItem(MENU_READY_STORAGE_KEY) || '').trim() === MENU_PAGE_TOKEN;
            } catch {
                return false;
            }
        }

        function queuePendingCommand(commandKey, commandId) {
            const key = normalizeCommandKey(commandKey);
            const id = String(commandId || "").trim() || createCommandId(key);
            if (!key || !id) return null;
            const pendingEntries = readPendingEntries();
            pendingEntries.push(Object.freeze({ id, key }));
            writePendingEntries(pendingEntries);
            return id;
        }

        function dispatchCommand(commandKey, commandId) {
            const key = normalizeCommandKey(commandKey);
            if (!key) return false;
            const id = String(commandId || "").trim() || createCommandId(key);
            const payload = Object.freeze({
                type: "__templateShortcutsMenuCommand",
                source: MENU_MESSAGE_SOURCE,
                siteId: SITE_ID,
                pageToken: MENU_PAGE_TOKEN,
                commandKey: key,
                commandId: id
            });
            try {
                if (scope && typeof scope.postMessage === 'function') {
                    scope.postMessage(payload, '*');
                    return true;
                }
            } catch {}
            if (!dispatchTarget || typeof CustomEvent !== 'function') return false;
            try {
                dispatchTarget.dispatchEvent(new CustomEvent("__templateShortcutsMenuCommand", {
                    detail: payload
                }));
                return true;
            } catch {
                return false;
            }
        }

        function invokeCommand(commandKey) {
            const key = normalizeCommandKey(commandKey);
            const commandId = createCommandId(key);
            if (!isCurrentPageMenuReady()) {
                queuePendingCommand(key, commandId);
            }
            const dispatched = dispatchCommand(key, commandId);
            if (dispatched) return;

            if (key === "settings" && typeof settingsHandler === 'function') {
                try {
                    settingsHandler();
                    return;
                } catch (error) {
                    console.error(`[${SITE_LABEL}] settings menu handler failed.`, error);
                    return;
                }
            }

            if (key === "settings") {
                console.warn(`[${SITE_LABEL}] settings menu clicked before handler was ready.`);
            }
        }

        function registerCommand(commandKey, label) {
            const key = normalizeCommandKey(commandKey);
            const text = String(label || "").trim();
            if (!key || !text || typeof register !== 'function') return null;

            const existing = commands.get(key) || null;
            if (existing && existing.label === text && existing.commandId !== null && existing.commandId !== undefined) {
                return existing.commandId;
            }

            if (existing && existing.commandId !== null && existing.commandId !== undefined && typeof unregister === 'function') {
                try { unregister(existing.commandId); } catch {}
            }

            let commandId = null;
            try {
                commandId = register(text, () => invokeCommand(key));
            } catch (error) {
                console.warn(`[${SITE_LABEL}] Failed to register bootstrap menu "${text}".`, error);
                commandId = null;
            }

            commands.set(key, { label: text, commandId });
            return commandId;
        }

        function unregisterCommand(commandKey) {
            const key = normalizeCommandKey(commandKey);
            if (!key) return false;
            const existing = commands.get(key) || null;
            if (!existing) return false;
            if (existing.commandId !== null && existing.commandId !== undefined && typeof unregister === 'function') {
                try { unregister(existing.commandId); } catch {}
            }
            commands.delete(key);
            return true;
        }

        function consumePending(commandKey) {
            const key = normalizeCommandKey(commandKey);
            if (!key) return 0;
            const pendingEntries = readPendingEntries();
            if (pendingEntries.length === 0) return 0;
            let count = 0;
            const remainingEntries = [];
            for (const entry of pendingEntries) {
                if (entry.key === key) {
                    count += 1;
                    continue;
                }
                remainingEntries.push(entry);
            }
            writePendingEntries(remainingEntries);
            return count;
        }

        registerCommand("settings", `${SITE_LABEL} - 设置快捷键`);
        for (const command of BOOTSTRAP_MENU_COMMANDS) {
            if (command?.key === "settings") continue;
            registerCommand(command?.key, command?.label);
        }

        const bridge = {
            managedByBootstrap: typeof register === 'function',
            eventName: "__templateShortcutsMenuCommand",
            registerCommand,
            unregisterCommand,
            consumePending,
            dispatchCommand,
            setSettingsHandler(handler) {
                settingsHandler = typeof handler === 'function' ? handler : null;
                return settingsHandler !== null;
            },
            getSettingsCommandId() {
                return commands.get("settings")?.commandId ?? null;
            },
            getSettingsLabel() {
                return commands.get("settings")?.label || `${SITE_LABEL} - 设置快捷键`;
            }
        };

        if (scope) {
            try {
                Object.defineProperty(scope, "__TEMPLATE_SHORTCUTS_MENU_BRIDGE__", {
                    value: bridge,
                    configurable: true,
                    enumerable: false,
                    writable: true
                });
            } catch {
                try {
                    scope["__TEMPLATE_SHORTCUTS_MENU_BRIDGE__"] = bridge;
                } catch {}
            }
        }

        return Object.freeze(bridge);
    }

    async function getResourceUrl(name) {
        const fn = getUserscriptApi('GM_getResourceURL');
        if (typeof fn !== 'function') {
            throw new Error(`GM_getResourceURL is unavailable for resource "${name}"`);
        }

        const value = await Promise.resolve(fn(name));
        const url = typeof value === 'string' ? value.trim() : '';
        if (!url) {
            throw new Error(`GM_getResourceURL returned an empty URL for resource "${name}"`);
        }
        return url;
    }

    async function prepareModuleUrl(name) {
        const rawUrl = await getResourceUrl(name);

        try {
            const response = await fetch(rawUrl);
            if (!response.ok) {
                throw new Error(`HTTP ${response.status}`);
            }

            const source = await response.text();
            const blob = new Blob([source], { type: 'text/javascript;charset=utf-8' });
            return {
                rawUrl,
                moduleUrl: URL.createObjectURL(blob)
            };
        } catch (error) {
            console.warn(`[${SITE_LABEL}] Failed to rewrap resource "${name}" as a module blob URL. Falling back to the original resource URL.`, error);
            return {
                rawUrl,
                moduleUrl: rawUrl
            };
        }
    }

    exposeUserscriptApiResolver();
    const menuBridge = createMenuBridge();

    async function main() {
        const preparedCore = await prepareModuleUrl(RESOURCE_NAMES.core);
        const preparedSite = await prepareModuleUrl(RESOURCE_NAMES.site);
        const resourceUrls = Object.freeze({
            core: preparedCore.rawUrl,
            site: preparedSite.rawUrl
        });
        const moduleUrls = Object.freeze({
            core: preparedCore.moduleUrl,
            site: preparedSite.moduleUrl
        });

        const siteModule = await import(moduleUrls.site);
        const startSite = typeof siteModule?.startSite === 'function'
            ? siteModule.startSite
            : (typeof siteModule?.default === 'function' ? siteModule.default : null);

        if (typeof startSite !== 'function') {
            throw new Error('Site module must export startSite(runtime).');
        }

        await startSite(Object.freeze({
            siteId: SITE_ID,
            displayName: SITE_LABEL,
            resourceNames: RESOURCE_NAMES,
            resourceUrls,
            moduleUrls,
            bootstrapMenuManaged: BOOTSTRAP_MENU_COMMANDS.length > 0,
            menuMessageType: "__templateShortcutsMenuCommand",
            menuMessageSource: "template-shortcuts-userscript",
            menuPendingStorageKey: MENU_PENDING_STORAGE_KEY,
            menuReadyStorageKey: MENU_READY_STORAGE_KEY,
            menuPageToken: MENU_PAGE_TOKEN,
            menuBridge,
            getUserscriptApi,
            getResourceUrl
        }));
    }

    void main().catch((error) => {
        console.error(`[${SITE_LABEL}] userscript bootstrap failed.`, error);
    });
})();
