// ==UserScript==
// @name           [Claude] 快捷键跳转 [20260508] v1.0.0
// @name:en        [Claude] Shortcut Jump [20260508] v1.0.0
// @namespace      https://github.com/0-V-linuxdo/Template_shortcuts.js
// @description    为 Claude AI 添加自定义快捷键(跳转/点击/模拟按键), 支持自定义 图标/快捷键/选择器/模拟按键, 适配暗黑模式。新增: 预设图标库(可折叠/自定义添加/长按删除)。功能包括: 侧边栏切换、新建话题、历史记录等快捷操作。基于Template模块重构。
// @description:en Adds visual custom shortcuts for Claude AI, including URL jumps, clicks, simulated keys, custom icons, dark mode, and a reusable icon library.

// @version        [20260508] v1.0.0
// @update-log     1.0.0: 保留原键帽样式，将 Claude 脚本图标键帽改为普通模式黑色、黑暗模式白色自适应。
// @update-log:en  1.0.0: Kept the original keycap style and made the Claude script icon keycap adapt to black in light mode and white in dark mode.

// @match          https://claude.ai/*

// @grant          GM_registerMenuCommand
// @grant          GM_getValue
// @grant          GM_setValue
// @grant          GM_xmlhttpRequest
// @grant          GM_unregisterMenuCommand

// @connect        *

// @icon           data:image/svg+xml,%3Csvg%20viewBox%3D%220%200%2064%2064%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20aria-hidden%3D%22true%22%20role%3D%22img%22%20preserveAspectRatio%3D%22xMidYMid%20meet%22%20class%3D%22claude-keycap-icon%22%3E%20%3Cstyle%3E%20%3Aroot%20%7B%20color-scheme%3A%20light%20dark%3B%20%7D%20.claude-keycap-icon%20%7B%20color%3A%20%23000000%3B%20%7D%20%40media%20(prefers-color-scheme%3A%20dark)%20%7B%20.claude-keycap-icon%20%7B%20color%3A%20%23FFFFFF%3B%20%7D%20%7D%20%3C%2Fstyle%3E%20%3Cpath%20d%3D%22M52%202H12C6.478%202%202%206.477%202%2011.999V52c0%205.522%204.478%2010%2010%2010h40c5.522%200%2010-4.478%2010-10V11.999C62%206.477%2057.522%202%2052%202zm5%2043.666A8.333%208.333%200%200%201%2048.667%2054H15.333A8.333%208.333%200%200%201%207%2045.666V12.333A8.332%208.332%200%200%201%2015.333%204h33.334A8.332%208.332%200%200%201%2057%2012.333v33.333z%22%20fill%3D%22currentColor%22%20fill-rule%3D%22evenodd%22%20clip-rule%3D%22evenodd%22%3E%3C%2Fpath%3E%20%3Cpath%20fill%3D%22%23d97757%22%20d%3D%22m19.798%2035.671%207.822-4.389.131-.38-.131-.213h-.381l-1.307-.08-4.47-.121-3.876-.161-3.755-.202-.945-.2-.886-1.17.091-.582.795-.534%201.138.099%202.515.172%203.774.26%202.738.161%204.056.422h.644l.092-.26-.22-.162-.172-.16-3.906-2.648-4.228-2.797-2.214-1.61-1.197-.816-.604-.765-.26-1.67%201.086-1.197%201.46.1.374.099%201.479%201.138%203.16%202.445%204.125%203.039.604.502.242-.172.03-.12-.272-.454-2.244-4.056-2.394-4.126-1.066-1.71-.282-1.025c-.1-.422-.172-.776-.172-1.208l1.238-1.68.684-.22%201.651.22.695.603%201.026%202.346%201.661%203.694%202.577%205.022.754%201.49.403%201.38.15.421h.26v-.241l.213-2.83.392-3.473.38-4.47.132-1.259.623-1.508L35.25%209.8l.966.462.795%201.138-.11.735-.473%203.071-.926%204.81-.604%203.222h.352l.402-.403%201.63-2.164%202.738-3.422%201.208-1.358%201.409-1.5.904-.715h1.71l1.26%201.871-.564%201.933-1.761%202.233-1.46%201.892-2.094%202.819-1.308%202.255.121.18.312-.03%204.73-1.007%202.555-.461%203.05-.524%201.379.645.15.655-.542%201.339-3.261.805-3.826.765-5.696%201.348-.07.05.081.1%202.566.242%201.098.059h2.687l5.004.373%201.307.864.784%201.058-.132.805-2.013%201.026-2.716-.645-6.34-1.508-2.175-.542h-.3v.18l1.811%201.771%203.32%202.998%204.159%203.866.212.955-.535.755-.563-.08-3.654-2.75-1.409-1.237-3.191-2.687h-.212v.282l.735%201.076%203.884%205.839.202%201.79-.282.582-1.007.352-1.106-.201-2.273-3.192-2.347-3.594-1.892-3.221-.23.131L32.58%2047.92l-.524.614-1.208.462-1.006-.765-.535-1.237.535-2.446.644-3.192.523-2.536.473-3.152.281-1.046-.018-.07-.231.03-2.376%203.26-3.613%204.883-2.859%203.06-.684.272-1.187-.615.11-1.098.664-.977%203.956-5.033%202.387-3.12%201.54-1.8-.01-.26h-.092l-10.509%206.823-1.87.241-.806-.754.1-1.237.38-.403%203.16-2.174-.01.01Z%22%3E%3C%2Fpath%3E%20%3C%2Fsvg%3E
// @require        https://github.com/0-V-linuxdo/Template_shortcuts.js/raw/refs/heads/release/Template_JS/%5BTemplate%5D%20shortcut%20core.js?v=20260504.1.0.0
// ==/UserScript==

/* ===================== IMPORTANT · NOTICE · START =====================
 *
 * 1. [编辑指引 | Edit Guidance]
 *    • ⚠️ 这是一个自动生成的文件：请不要直接修改当前产物。
 *    • ⚠️ 源码真源位于当前仓库 `main` 分支的 `src/modules/` 与 `src/sites/`；站点元数据位于 `src/sites/manifest.js`；Template 头部元数据位于 `src/userscript/header.txt`。
 *    • ⚠️ 在 `main` 分支运行 `npm run build` 会刷新本地 `Template_JS/` 与 `Site_JS/`。
 *    • ⚠️ 最新发布物应同步到当前仓库的 `release` 分支；release userscript 通过 `@require` 加载 `Template_JS/[Template] shortcut core.js`；`archive/` 仅保存历史归档与参考资料，不参与当前运行时加载。
 *    • ⚠️ This is a generated artifact. Do not edit this file directly. The source of truth lives in the current repository's `main` branch under `src/modules/`, `src/sites/`, `src/sites/manifest.js`, and `src/userscript/header.txt`. Run `npm run build` on `main` to refresh local `Template_JS/` and `Site_JS/` outputs, then stage release assets for the repository's `release` branch.
 *
 * ----------------------------------------------------------------------
 *
 * 2. [安全提示 | Safety Reminder]
 *    • ✅ 必须使用 `setTrustedHTML`，不得使用 `innerHTML`。
 *    • ✅ Always call `setTrustedHTML`; never rely on `innerHTML`.
 *
 * ====================== IMPORTANT · NOTICE · END ======================
 */

(() => {
  // src/sites/claude/index.js
  (function() {
    "use strict";
    const ShortcutTemplate = window.ShortcutTemplate;
    if (!ShortcutTemplate || typeof ShortcutTemplate.createShortcutEngine !== "function") {
      console.error("[Claude Shortcut] Template module not found.");
      return;
    }
    const defaultIconURL = "https://claude.ai/favicon.ico";
    const STORAGE_KEYS = {
      shortcuts: "claude_shortcuts_v1",
      iconCachePrefix: "claude_icon_cache_v1::",
      userIcons: "claude_user_icons_v1"
    };
    const defaultIcons = [
      { name: "Claude AI", url: "https://claude.ai/favicon.ico" },
      { name: "Claude Icon Alt", url: "https://claude.ai/images/claude_app_icon.png" },
      { name: "OpenAI", url: "https://cdn.openai.com/API/favicon-32x32.png" },
      { name: "ChatGPT", url: "https://chat.openai.com/favicon-32x32.png" },
      { name: "Google", url: "https://www.google.com/favicon.ico" },
      { name: "Bing", url: "https://www.bing.com/favicon.ico" },
      { name: "DuckDuckGo", url: "https://duckduckgo.com/favicon.ico" },
      { name: "Baidu", url: "https://www.baidu.com/favicon.ico" },
      { name: "Wikipedia", url: "https://www.wikipedia.org/static/favicon/wikipedia.ico" },
      { name: "Reddit", url: "https://www.reddit.com/favicon.ico" },
      { name: "Stack Overflow", url: "https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico" },
      { name: "GitHub", url: "https://github.githubassets.com/favicons/favicon.svg" },
      { name: "Twitter / X", url: "https://abs.twimg.com/favicons/twitter.3.ico" },
      { name: "Bilibili", url: "https://www.bilibili.com/favicon.ico" },
      { name: "YouTube", url: "https://www.youtube.com/favicon.ico" }
    ];
    const protectedIconUrls = [
      "https://claude.ai/favicon.ico",
      "https://claude.ai/images/claude_app_icon.png"
    ];
    const SITE_MESSAGES = Object.freeze({
      "zh-CN": {
        menuCommandLabel: "Claude - 设置快捷键",
        panelTitle: "Claude - 自定义快捷键",
        shortcuts: {
          "Toggle Sidebar": "切换侧边栏",
          "New Conversation": "新建对话",
          "Recent Conversations": "最近对话",
          "Incognito Chat": "无痕聊天",
          "Star Conversation": "收藏对话",
          "Delete Conversation": "删除对话",
          "Stop Claude's Response": "停止 Claude 回复",
          "Extended thinking": "扩展思考",
          "web": "网页搜索",
          "Profile": "个人资料",
          "Features": "功能设置"
        },
        dataAdapters: {
          toolMenu: {
            label: "菜单关键词（或粘贴 JSON，高级用法）:",
            placeholder: "例如: web / Web search / 网页搜索 / 联网搜索"
          },
          conversationMenu: {
            label: "Conversation menu 关键词（或粘贴 JSON，高级用法）:",
            placeholder: "例如: Star / Rename / Add to project / Delete"
          }
        }
      },
      "en-US": {
        menuCommandLabel: "Claude - Shortcut settings",
        panelTitle: "Claude - Custom shortcuts",
        dataAdapters: {
          toolMenu: {
            label: "Menu keyword (or paste JSON, advanced):",
            placeholder: "Example: web / Web search / Web"
          },
          conversationMenu: {
            label: "Conversation menu keyword (or paste JSON, advanced):",
            placeholder: "Example: Star / Rename / Add to project / Delete"
          }
        }
      }
    });
    const siteText = (key, fallback) => ({ ctx } = {}) => ctx?.i18n?.t?.(key, {}, fallback) || fallback;
    const CLAUDE_MENU_ITEM_SELECTOR = "[role='menuitem'], [role='menuitemcheckbox'], [role='menuitemradio']";
    const CLAUDE_WEB_SELECTORS = {
      moreButton: "button[aria-haspopup='menu'][aria-label='Toggle menu']",
      dropdownMenu: "div.z-dropdown [role='menu']",
      menuItem: CLAUDE_MENU_ITEM_SELECTOR
    };
    const CLAUDE_CONVERSATION_MENU_SELECTORS = {
      triggerButton: "button[data-testid='chat-menu-trigger'][aria-haspopup='menu']",
      dropdownMenu: "[role='menu'][data-radix-menu-content]",
      menuItem: CLAUDE_MENU_ITEM_SELECTOR,
      starItem: "[data-testid='star-chat-trigger']",
      deleteItem: "[data-testid='delete-chat-trigger']"
    };
    const TemplateUtils = ShortcutTemplate.utils;
    if (!TemplateUtils?.menu?.createMenuController) {
      console.error("[Claude Shortcut] Template utils.menu not found (update Template core).");
      return;
    }
    const moreMenu = TemplateUtils.menu.createMenuController({
      trigger: {
        selector: CLAUDE_WEB_SELECTORS.moreButton,
        pick: "preferSvgPath",
        preferSvgPathDIncludes: ["V9.5H16.5", "H3.5"]
      },
      root: {
        type: "ariaLabelledBy",
        selector: CLAUDE_WEB_SELECTORS.dropdownMenu
      }
    });
    const conversationMenu = TemplateUtils.menu.createMenuController({
      trigger: {
        selector: CLAUDE_CONVERSATION_MENU_SELECTORS.triggerButton,
        pick: "last"
      },
      root: {
        type: "ariaLabelledBy",
        selector: CLAUDE_CONVERSATION_MENU_SELECTORS.dropdownMenu
      }
    });
    const DEFAULT_WEB_TEXT_MATCH = ["web search", "web 搜索", "网页搜索", "联网搜索"];
    const DEFAULT_WEB_FALLBACK_TO_FIRST = true;
    function normalizeMenuToken(value) {
      return String(value ?? "").trim();
    }
    function normalizeMenuKey(value) {
      return normalizeMenuToken(value).toLowerCase();
    }
    function normalizeMenuAction(value, fallback = "onestep") {
      const token = normalizeMenuToken(value).toLowerCase();
      return token || fallback;
    }
    function hasValidTextMatch(textMatch) {
      if (typeof textMatch === "string") return !!textMatch.trim();
      if (textMatch instanceof RegExp) return true;
      if (typeof textMatch === "function") return true;
      if (Array.isArray(textMatch)) return textMatch.some((v) => hasValidTextMatch(v));
      return false;
    }
    function describeSelectorSpec(value) {
      if (typeof value === "string") {
        const trimmed = value.trim();
        return { provided: !!trimmed, hasLiteral: !!trimmed };
      }
      if (Array.isArray(value)) {
        return {
          provided: value.some((item) => describeSelectorSpec(item).provided),
          hasLiteral: value.some((item) => describeSelectorSpec(item).hasLiteral)
        };
      }
      if (value && typeof value === "object") {
        const hasLiteral = typeof value.selector === "string" && !!value.selector.trim() || typeof value.fallback === "string" && !!value.fallback.trim() || Array.isArray(value.selectors) && value.selectors.some((item) => describeSelectorSpec(item).hasLiteral);
        return { provided: true, hasLiteral };
      }
      return { provided: false, hasLiteral: false };
    }
    function getClaudeMenuActionSpec(shortcut, {
      actionName,
      menuController,
      defaultItemSelector = CLAUDE_WEB_SELECTORS.menuItem,
      defaultTextMatch = null,
      defaultAction = "onestep",
      defaultFallbackToFirst = false,
      defaultWaitForItem = true
    } = {}) {
      const data = shortcut && typeof shortcut.data === "object" && !Array.isArray(shortcut.data) ? shortcut.data : {};
      const rawMenu = data.menu;
      const menu = rawMenu && typeof rawMenu === "object" && !Array.isArray(rawMenu) ? rawMenu : rawMenu !== void 0 ? { textMatch: rawMenu } : data;
      const path = Array.isArray(menu.path) ? menu.path : null;
      const pathParts = path ? path.map(normalizeMenuToken).filter(Boolean) : [];
      const presetKey = normalizeMenuKey(menu.preset ?? data.preset);
      const keywordToken = menu.keyword !== void 0 ? menu.keyword : menu.textMatch;
      const keywordKey = typeof keywordToken === "string" ? normalizeMenuKey(keywordToken) : "";
      const pathLastKey = pathParts.length ? normalizeMenuKey(pathParts[pathParts.length - 1]) : "";
      const isWebPreset = presetKey === "web" || keywordKey === "web" || pathLastKey === "web";
      const effectiveDefaultTextMatch = isWebPreset ? DEFAULT_WEB_TEXT_MATCH : defaultTextMatch;
      const effectiveDefaultFallbackToFirst = isWebPreset ? DEFAULT_WEB_FALLBACK_TO_FIRST : defaultFallbackToFirst;
      const action = normalizeMenuAction(menu.action, defaultAction);
      const fallbackToFirst = menu.fallbackToFirst !== void 0 ? !!menu.fallbackToFirst : !!effectiveDefaultFallbackToFirst;
      const waitForItem = menu.waitForItem !== void 0 ? !!menu.waitForItem : !!defaultWaitForItem;
      const allowFirstItem = !!menu.allowFirstItem;
      let textMatch = menu.keyword !== void 0 ? menu.keyword : menu.textMatch;
      if ((textMatch === void 0 || textMatch === null || textMatch === "") && pathParts.length) {
        textMatch = pathParts[pathParts.length - 1];
      }
      if (typeof textMatch === "string" && normalizeMenuKey(textMatch) === "web" && effectiveDefaultTextMatch) {
        textMatch = effectiveDefaultTextMatch;
      }
      if (textMatch === void 0 || textMatch === null || textMatch === "") textMatch = effectiveDefaultTextMatch;
      const openSubmenus = [];
      if (Array.isArray(menu.openSubmenus)) openSubmenus.push(...menu.openSubmenus);
      if (pathParts.length > 1) openSubmenus.push(...pathParts.slice(0, -1));
      const normalizedOpenSubmenus = Array.from(new Set(openSubmenus.map(normalizeMenuKey).filter(Boolean)));
      const submenuKey = normalizeMenuKey(menu.submenuKey || (normalizedOpenSubmenus[0] || ""));
      const rawSelector = menu.selector;
      const { provided: selectorProvided, hasLiteral: selectorHasLiteral } = describeSelectorSpec(rawSelector);
      const selector = selectorProvided ? typeof rawSelector === "string" ? rawSelector.trim() : rawSelector : defaultItemSelector || "";
      const selectorMaybeEmpty = selectorProvided && !selectorHasLiteral && action !== "open" && action !== "submenu";
      if (action === "submenu" && !submenuKey) {
        console.warn(`[Claude Shortcut] ${actionName || "menu"}: missing submenuKey; set data.menu.submenuKey (or set data.menu.openSubmenus/path).`);
        return null;
      }
      return {
        actionName,
        menu: menuController,
        defaultItemSelector,
        action,
        selector,
        selectorProvided,
        selectorMaybeEmpty,
        textMatch: allowFirstItem ? null : textMatch,
        fallbackToFirst,
        waitForItem,
        allowFirstItem,
        openSubmenus: normalizedOpenSubmenus,
        submenuKey
      };
    }
    function ensureMenuTarget(spec) {
      if (spec.allowFirstItem || hasValidTextMatch(spec.textMatch) || spec.selectorProvided) return true;
      console.warn(`[Claude Shortcut] ${spec.actionName || "menu"}: missing menu target; set data.menu = "web" / "Web search" (or set data.menu.textMatch / data.menu.keyword / data.menu.path), or set data.menu.allowFirstItem=true to click the first item.`);
      return false;
    }
    async function runMenuSelection(spec, engine2, mode) {
      const common = {
        textMatch: spec.textMatch,
        fallbackToFirst: spec.fallbackToFirst,
        waitForItem: spec.waitForItem
      };
      const run = (selector) => {
        if (mode === "click") {
          return spec.menu.clickInOpenMenus({ engine: engine2 }, { selector, ...common });
        }
        return spec.menu.oneStepClick(
          { engine: engine2 },
          { selector, openSubmenus: spec.openSubmenus, ...common }
        );
      };
      let ok = await run(spec.selector);
      if (ok || !spec.selectorMaybeEmpty || !hasValidTextMatch(spec.textMatch)) return ok;
      console.warn(`[Claude Shortcut] ${spec.actionName || "menu"}: menu.selector resolved to empty; fallback to default item selector.`);
      ok = await run(spec.defaultItemSelector);
      return ok;
    }
    function createClaudeMenuAction({ actionName, menuController, defaultItemSelector } = {}) {
      return async function claudeMenuAction({ shortcut, engine: engine2 }) {
        const spec = getClaudeMenuActionSpec(shortcut, { actionName, menuController, defaultItemSelector });
        if (!spec?.menu) return false;
        switch (spec.action) {
          case "open": {
            return await spec.menu.ensureOpen({ engine: engine2 });
          }
          case "submenu": {
            if (!spec.submenuKey) return false;
            return await spec.menu.ensureSubmenuOpen({ engine: engine2 }, spec.submenuKey);
          }
          case "click": {
            if (!ensureMenuTarget(spec)) return false;
            return await runMenuSelection(spec, engine2, "click");
          }
          default: {
            if (!ensureMenuTarget(spec)) return false;
            return await runMenuSelection(spec, engine2, "oneStep");
          }
        }
      };
    }
    function createClaudeMenuDataAdapter({
      label = "菜单关键词（或粘贴 JSON，高级用法）:",
      placeholder = ""
    } = {}) {
      return {
        label,
        placeholder,
        format: (data) => {
          const raw = data && typeof data === "object" && !Array.isArray(data) ? data : {};
          const keys = Object.keys(raw);
          if (keys.length === 0) return "";
          const menu = raw.menu;
          if (typeof menu === "string" && menu.trim()) return menu.trim();
          if (menu && typeof menu === "object" && !Array.isArray(menu)) {
            const menuKeys = Object.keys(menu);
            const keyword = typeof menu.keyword === "string" && menu.keyword.trim() ? menu.keyword.trim() : typeof menu.textMatch === "string" && menu.textMatch.trim() ? menu.textMatch.trim() : "";
            if (keyword && menuKeys.every((k) => ["keyword", "textMatch"].includes(k))) return keyword;
          }
          if (keys.length === 1 && keys[0] === "keyword" && typeof raw.keyword === "string" && raw.keyword.trim()) {
            return raw.keyword.trim();
          }
          if (keys.length === 1 && keys[0] === "textMatch" && typeof raw.textMatch === "string" && raw.textMatch.trim()) {
            return raw.textMatch.trim();
          }
          if (keys.length === 1 && keys[0] === "path" && Array.isArray(raw.path)) {
            const parts = raw.path.map((value) => String(value ?? "").trim()).filter(Boolean);
            if (parts.length === 1) return parts[0];
          }
          try {
            return JSON.stringify(raw, null, 2);
          } catch {
            return "";
          }
        },
        parse: (text) => {
          const trimmed = String(text ?? "").trim();
          if (!trimmed) return {};
          if (trimmed.startsWith("{") || trimmed.startsWith("[")) {
            const parsed = JSON.parse(trimmed);
            if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error("data must be an object");
            return parsed;
          }
          return { menu: trimmed };
        }
      };
    }
    const CLAUDE_MENU_DATA_ADAPTER = createClaudeMenuDataAdapter({
      label: siteText("dataAdapters.toolMenu.label", "Menu keyword (or paste JSON, advanced):"),
      placeholder: siteText("dataAdapters.toolMenu.placeholder", "Example: web / Web search")
    });
    const CLAUDE_CONVERSATION_MENU_DATA_ADAPTER = createClaudeMenuDataAdapter({
      label: siteText("dataAdapters.conversationMenu.label", "Conversation menu keyword (or paste JSON, advanced):"),
      placeholder: siteText("dataAdapters.conversationMenu.placeholder", "Example: Star / Rename / Add to project / Delete")
    });
    const CUSTOM_ACTIONS = {
      toolMenu: createClaudeMenuAction({
        actionName: "toolMenu",
        menuController: moreMenu,
        defaultItemSelector: CLAUDE_WEB_SELECTORS.menuItem
      }),
      conversationMenu: createClaudeMenuAction({
        actionName: "conversationMenu",
        menuController: conversationMenu,
        defaultItemSelector: CLAUDE_CONVERSATION_MENU_SELECTORS.menuItem
      })
    };
    const baseShortcut = {
      url: "",
      urlMethod: "current",
      urlAdvanced: "href",
      selector: "",
      simulateKeys: "",
      icon: defaultIconURL
    };
    const createShortcut = (overrides) => ({ ...baseShortcut, ...overrides });
    const defaultShortcuts = [
      createShortcut({ name: "Toggle Sidebar", actionType: "simulate", simulateKeys: "META+.", hotkey: "CTRL+B" }),
      createShortcut({ name: "New Conversation", actionType: "url", url: "https://claude.ai/new", hotkey: "CTRL+N" }),
      createShortcut({ name: "Recent Conversations", actionType: "url", url: "https://claude.ai/recents", hotkey: "CTRL+H" }),
      createShortcut({ name: "Incognito Chat", actionType: "simulate", simulateKeys: "SHIFT+META+I", hotkey: "CTRL+I" }),
      createShortcut({
        name: "Star Conversation",
        actionType: "custom",
        customAction: "conversationMenu",
        data: { menu: "Star" },
        hotkey: "CTRL+S"
      }),
      createShortcut({
        name: "Delete Conversation",
        actionType: "custom",
        customAction: "conversationMenu",
        data: { menu: "Delete" },
        hotkey: "CTRL+BACKSPACE"
      }),
      createShortcut({ name: "Stop Claude's Response", actionType: "simulate", simulateKeys: "ESC", hotkey: "CTRL+SHIFT+S" }),
      createShortcut({ name: "Extended thinking", actionType: "simulate", simulateKeys: "SHIFT+META+E", hotkey: "CTRL+T" }),
      createShortcut({ name: "web", actionType: "custom", customAction: "toolMenu", data: { menu: "web" }, hotkey: "CTRL+W" }),
      createShortcut({ name: "Profile", actionType: "url", url: "https://claude.ai/settings/profile", hotkey: "CTRL+SHIFT+P" }),
      createShortcut({ name: "Features", actionType: "url", url: "https://claude.ai/settings/features", hotkey: "CTRL+SHIFT+F" })
    ];
    const engine = ShortcutTemplate.createShortcutEngine({
      // 基本配置
      menuCommandLabel: "Claude - 设置快捷键",
      panelTitle: "Claude - 自定义快捷键",
      // 存储键配置
      storageKeys: STORAGE_KEYS,
      // UI配置
      ui: {
        idPrefix: "claude"
      },
      i18n: {
        messages: SITE_MESSAGES
      },
      // 图标配置
      defaultIconURL,
      iconLibrary: defaultIcons,
      protectedIconUrls,
      // 默认快捷键
      defaultShortcuts,
      // 自定义动作表：将 1step/复杂点击动作纳入引擎
      customActions: CUSTOM_ACTIONS,
      // 自定义动作 data 编辑器适配：让用户直接输入关键词（无需 JSON）
      customActionDataAdapters: {
        toolMenu: CLAUDE_MENU_DATA_ADAPTER,
        conversationMenu: CLAUDE_CONVERSATION_MENU_DATA_ADAPTER
      },
      // 控制台标签
      consoleTag: "[Claude Shortcut Script]",
      // 主题色配置
      colors: {
        primary: "#5D5CDE"
        // Claude的主色调
      },
      // Claude特定的图标缓存绕过规则
      shouldBypassIconCache: (url) => {
        return url && url.startsWith("https://claude.ai/");
      }
    });
    engine.init();
  })();
})();
