// ==UserScript==
// @name         [Gemini] 快捷键跳转 [20260423] v1.0.2
// @namespace    https://github.com/0-V-linuxdo/Template_shortcuts.js
// @description  为 Gemini 提供可视化自定义快捷键：快速新建会话、切换模型、打开工具、Pin/Delete 对话与快捷输入发送，支持按键和图标自定义。

// @version      [20260423] v1.0.2
// @update-log   1.0.2: 补齐 userscript bootstrap 与 ESM core 之间的 GM API 桥接，修复 Gemini 菜单命令仍不显示的问题。

// @match        https://gemini.google.com/*

// @grant        GM_registerMenuCommand
// @grant        GM_unregisterMenuCommand
// @grant        GM_getValue
// @grant        GM_setValue
// @grant        GM_xmlhttpRequest
// @grant        GM_getResourceURL

// @connect      *

// @icon         https://github.com/0-V-linuxdo/Template_shortcuts.js/raw/refs/heads/main/Site_Icon/gemini_keycap.svg
// @resource     template-core https://github.com/0-V-linuxdo/Template_shortcuts.js/raw/refs/heads/release/dist/esm/template-core.js
// @resource     site-entry https://github.com/0-V-linuxdo/Template_shortcuts.js/raw/refs/heads/release/dist/esm/sites/gemini.js
// ==/UserScript==

/* ===================== IMPORTANT · NOTICE · START =====================
 *
 * 1. [编辑指引 | Edit Guidance]
 *    • ⚠️ 这是一个自动生成的文件：请不要直接修改当前产物。
 *    • ⚠️ 源码真源位于当前仓库 `main` 分支的 `src/modules/` 与 `src/sites/`；userscript bootstrap 模板位于 `src/userscript/entry.js`；站点元数据位于 `src/sites/manifest.js`；Template 归档头部元数据位于 `src/userscript/header.txt`。
 *    • ⚠️ 在 `main` 分支运行 `npm run build` 会刷新本地 `dist/esm/`、`Site_JS/` 与 `archive/Template_JS/[Template] shortcut core.js`。
 *    • ⚠️ 最新发布物应同步到当前仓库的 `release` 分支；`archive/` 仅保存历史归档与参考资料，不参与当前 userscript 运行时加载。
 *    • ⚠️ This is a generated artifact. Do not edit this file directly. The source of truth lives in the current repository's `main` branch under `src/modules/`, `src/sites/`, `src/userscript/entry.js`, `src/sites/manifest.js`, and `src/userscript/header.txt`. Run `npm run build` on `main` to refresh local outputs, then stage release assets for the repository's `release` branch.
 *
 * ----------------------------------------------------------------------
 *
 * 2. [安全提示 | Safety Reminder]
 *    • ✅ 必须使用 `setTrustedHTML`，不得使用 `innerHTML`。
 *    • ✅ Always call `setTrustedHTML`; never rely on `innerHTML`.
 *
 * ====================== IMPORTANT · NOTICE · END ======================
 */

(() => {
    'use strict';

    const SITE_ID = "gemini";
    const SITE_LABEL = "[Gemini] 快捷键跳转";
    const RESOURCE_NAMES = Object.freeze({
    "core": "template-core",
    "site": "site-entry"
});

    function getGlobalScope() {
        return typeof globalThis !== 'undefined' ? globalThis : null;
    }

    function getDirectUserscriptApi(name) {
        switch (String(name || "")) {
            case 'GM_getValue':
                return typeof GM_getValue === 'function' ? GM_getValue : null;
            case 'GM_setValue':
                return typeof GM_setValue === 'function' ? GM_setValue : null;
            case 'GM_xmlhttpRequest':
                return typeof GM_xmlhttpRequest === 'function' ? GM_xmlhttpRequest : null;
            case 'GM_getResourceURL':
                return typeof GM_getResourceURL === 'function' ? GM_getResourceURL : null;
            case 'GM_registerMenuCommand':
                return typeof GM_registerMenuCommand === 'function' ? GM_registerMenuCommand : null;
            case 'GM_unregisterMenuCommand':
                return typeof GM_unregisterMenuCommand === 'function' ? GM_unregisterMenuCommand : null;
            default:
                return null;
        }
    }

    function getUserscriptApi(name) {
        const directBinding = getDirectUserscriptApi(name);
        if (typeof directBinding === 'function') return directBinding;

        const scope = getGlobalScope();
        if (!scope) return null;

        const direct = scope[name];
        if (typeof direct === 'function') return direct.bind(scope);

        const gm = scope.GM;
        if (gm && typeof gm === 'object') {
            const altName = name.replace(/^GM_/, '');
            const directGm = gm[altName];
            if (typeof directGm === 'function') return directGm.bind(gm);

            const lowerCamel = altName.charAt(0).toLowerCase() + altName.slice(1);
            const camelGm = gm[lowerCamel];
            if (typeof camelGm === 'function') return camelGm.bind(gm);
        }

        return null;
    }

    function exposeUserscriptApiResolver() {
        const scope = getGlobalScope();
        if (!scope) return;

        try {
            Object.defineProperty(scope, "__TEMPLATE_SHORTCUTS_GET_USERSCRIPT_API__", {
                value: getUserscriptApi,
                configurable: true,
                enumerable: false,
                writable: true
            });
            return;
        } catch {}

        try {
            scope["__TEMPLATE_SHORTCUTS_GET_USERSCRIPT_API__"] = getUserscriptApi;
        } catch {}
    }

    async function getResourceUrl(name) {
        const fn = getUserscriptApi('GM_getResourceURL');
        if (typeof fn !== 'function') {
            throw new Error(`GM_getResourceURL is unavailable for resource "${name}"`);
        }

        const value = await Promise.resolve(fn(name));
        const url = typeof value === 'string' ? value.trim() : '';
        if (!url) {
            throw new Error(`GM_getResourceURL returned an empty URL for resource "${name}"`);
        }
        return url;
    }

    async function prepareModuleUrl(name) {
        const rawUrl = await getResourceUrl(name);

        try {
            const response = await fetch(rawUrl);
            if (!response.ok) {
                throw new Error(`HTTP ${response.status}`);
            }

            const source = await response.text();
            const blob = new Blob([source], { type: 'text/javascript;charset=utf-8' });
            return {
                rawUrl,
                moduleUrl: URL.createObjectURL(blob)
            };
        } catch (error) {
            console.warn(`[${SITE_LABEL}] Failed to rewrap resource "${name}" as a module blob URL. Falling back to the original resource URL.`, error);
            return {
                rawUrl,
                moduleUrl: rawUrl
            };
        }
    }

    exposeUserscriptApiResolver();

    async function main() {
        const preparedCore = await prepareModuleUrl(RESOURCE_NAMES.core);
        const preparedSite = await prepareModuleUrl(RESOURCE_NAMES.site);
        const resourceUrls = Object.freeze({
            core: preparedCore.rawUrl,
            site: preparedSite.rawUrl
        });
        const moduleUrls = Object.freeze({
            core: preparedCore.moduleUrl,
            site: preparedSite.moduleUrl
        });

        const siteModule = await import(moduleUrls.site);
        const startSite = typeof siteModule?.startSite === 'function'
            ? siteModule.startSite
            : (typeof siteModule?.default === 'function' ? siteModule.default : null);

        if (typeof startSite !== 'function') {
            throw new Error('Site module must export startSite(runtime).');
        }

        await startSite(Object.freeze({
            siteId: SITE_ID,
            displayName: SITE_LABEL,
            resourceNames: RESOURCE_NAMES,
            resourceUrls,
            moduleUrls,
            getUserscriptApi,
            getResourceUrl
        }));
    }

    void main().catch((error) => {
        console.error(`[${SITE_LABEL}] userscript bootstrap failed.`, error);
    });
})();
