// ==UserScript==
// @name           [Grok] 快捷键跳转 [20260518] v1.0.0
// @name:en        [Grok] Shortcut Jump [20260518] v1.0.0
// @namespace      0_V userscripts/[Grok] 快捷键跳转
// @description    为Grok网站添加快捷键功能，支持自定义按键和图标，以及自动选择，完美适配暗黑模式。新增: 动作类型系统(URL跳转/元素点击/按键模拟)、预设图标库(可折叠/自定义添加/长按删除)、图标缓存机制。使用Template模块重构。
// @description:en Adds custom shortcuts for Grok with configurable keys and icons, dark mode support, action types, a preset icon library, and icon caching.

// @version        [20260518] v1.0.0
// @update-log     1.0.0: 删除 Switch user 快捷键，新增 Admin 后台跳转至 https://grok.dairoot.cn/admin，并为 Grok 默认快捷键图标启用普通/黑暗模式自适应。
// @update-log:en  1.0.0: Removed the Switch user shortcut, added the Admin URL jump to https://grok.dairoot.cn/admin, and enabled light/dark adaptive icons for Grok default shortcuts.

// @match          https://grok.dairoot.cn/*
// @match          https://grok.com/*

// @grant          GM_registerMenuCommand
// @grant          GM_unregisterMenuCommand
// @grant          GM_getValue
// @grant          GM_setValue
// @grant          GM_xmlhttpRequest

// @connect        *

// @icon           data:image/svg+xml,%3Csvg%20viewBox%3D%220%200%2064%2064%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20aria-hidden%3D%22true%22%20role%3D%22img%22%20preserveAspectRatio%3D%22xMidYMid%20meet%22%20class%3D%22grok-keycap-icon%22%3E%20%3Cstyle%3E%20%3Aroot%20%7B%20color-scheme%3A%20light%20dark%3B%20%7D%20.grok-keycap-icon%20%7B%20color%3A%20%23000000%3B%20%7D%20%40media%20(prefers-color-scheme%3A%20dark)%20%7B%20.grok-keycap-icon%20%7B%20color%3A%20%23FFFFFF%3B%20%7D%20%7D%20%3C%2Fstyle%3E%20%3Cpath%20d%3D%22M52%202H12C6.478%202%202%206.477%202%2011.999V52c0%205.522%204.478%2010%2010%2010h40c5.522%200%2010-4.478%2010-10V11.999C62%206.477%2057.522%202%2052%202zm5%2043.666A8.333%208.333%200%200%201%2048.667%2054H15.333A8.333%208.333%200%200%201%207%2045.666V12.333A8.332%208.332%200%200%201%2015.333%204h33.334A8.332%208.332%200%200%201%2057%2012.333v33.333z%22%20fill%3D%22currentColor%22%20fill-rule%3D%22evenodd%22%20clip-rule%3D%22evenodd%22%3E%3C%2Fpath%3E%20%3Cg%20transform%3D%22translate(13%2C10)%20scale(0.16)%22%20fill%3D%22currentColor%22%20fill-rule%3D%22evenodd%22%3E%3Cpath%20d%3D%22m92.7%20152.9%2079.78%20-58.97c3.91%20-2.9%209.5%20-1.77%2011.37%202.72%209.8%2023.69%205.42%2052.15%20-14.1%2071.69s-46.67%2023.82%20-71.49%2014.06l-27.11%2012.57c38.89%2026.61%2086.11%2020.03%20115.62%20-9.53%2023.41%20-23.44%2030.66%20-55.39%2023.88%20-84.2l0.06%200.07c-9.83%20-42.32%202.42%20-59.24%2027.5%20-93.83Q239.11%206.25%20240%205l-33.01%2033.05v-0.1L92.67%20152.92m-16.44%2014.31c-27.92%20-26.7%20-23.1%20-68.01%200.71%20-91.84%2017.61%20-17.63%2046.47%20-24.83%2071.66%20-14.25l27.05%20-12.5a78%2078%200%200%200%20-18.29%20-10A89.75%2089.75%200%200%200%2059.84%2058.3c-25.33%2025.36%20-33.3%2064.36%20-19.62%2097.64%2010.22%2024.87%20-6.53%2042.46%20-23.4%2060.22%20-5.99%206.3%20-11.99%2012.59%20-16.82%2019.25l76.2%20-68.15%22%3E%3C%2Fpath%3E%3C%2Fg%3E%20%3C%2Fsvg%3E
// @require        https://github.com/0-V-linuxdo/Template_shortcuts.js/raw/refs/heads/release/Template_JS/%5BTemplate%5D%20shortcut%20core.js?v=20260517.1.0.0
// ==/UserScript==

/* ===================== IMPORTANT · NOTICE · START =====================
 *
 * 1. [编辑指引 | Edit Guidance]
 *    • ⚠️ 这是一个自动生成的文件：请不要直接修改当前产物。
 *    • ⚠️ 源码真源位于当前仓库 `main` 分支的 `src/modules/` 与 `src/sites/`；站点元数据位于 `src/sites/manifest.js`；Template 头部元数据位于 `src/userscript/header.txt`。
 *    • ⚠️ 在 `main` 分支运行 `npm run build` 会刷新本地 `Template_JS/` 与 `Site_JS/`。
 *    • ⚠️ 最新发布物应同步到当前仓库的 `release` 分支；release userscript 通过 `@require` 加载 `Template_JS/[Template] shortcut core.js`；`archive/` 仅保存历史归档与参考资料，不参与当前运行时加载。
 *    • ⚠️ This is a generated artifact. Do not edit this file directly. The source of truth lives in the current repository's `main` branch under `src/modules/`, `src/sites/`, `src/sites/manifest.js`, and `src/userscript/header.txt`. Run `npm run build` on `main` to refresh local `Template_JS/` and `Site_JS/` outputs, then stage release assets for the repository's `release` branch.
 *
 * ----------------------------------------------------------------------
 *
 * 2. [安全提示 | Safety Reminder]
 *    • ✅ 必须使用 `setTrustedHTML`，不得使用 `innerHTML`。
 *    • ✅ Always call `setTrustedHTML`; never rely on `innerHTML`.
 *
 * ====================== IMPORTANT · NOTICE · END ======================
 */

(() => {
  // src/sites/grok/index.js
  (function() {
    "use strict";
    function gmGetValueLocal(key, fallback) {
      if (typeof GM_getValue !== "function") return fallback;
      try {
        const value = GM_getValue(key, fallback);
        return value === void 0 ? fallback : value;
      } catch {
        return fallback;
      }
    }
    function gmSetValueLocal(key, value) {
      if (typeof GM_setValue !== "function") return;
      try {
        GM_setValue(key, value);
      } catch {
      }
    }
    function gmRegisterMenuCommandLocal(label, handler) {
      if (typeof GM_registerMenuCommand !== "function") return null;
      try {
        return GM_registerMenuCommand(label, handler);
      } catch {
        return null;
      }
    }
    function gmUnregisterMenuCommandLocal(commandId) {
      if (typeof GM_unregisterMenuCommand !== "function") return;
      try {
        GM_unregisterMenuCommand(commandId);
      } catch {
      }
    }
    function getLocalStorageLocal() {
      try {
        return globalThis.localStorage || null;
      } catch {
        return null;
      }
    }
    const ShortcutTemplate = window.ShortcutTemplate;
    if (!ShortcutTemplate || typeof ShortcutTemplate.createShortcutEngine !== "function") {
      console.error("[Grok Shortcut] Template module not found.");
      return;
    }
    const LOG_TAG = "[Grok Shortcut Script]";
    const TemplateUtils = ShortcutTemplate?.utils || {};
    function svgDataUrlLocal(svgText) {
      const source = String(svgText || "").trim().replace(/\s+/g, " ");
      return source ? `data:image/svg+xml,${encodeURIComponent(source)}` : "";
    }
    const GROK_ADMIN_URL = "https://grok.dairoot.cn/admin";
    const GROK_LEGACY_SWITCH_USER_NAME_ZH = "用户切换";
    const GROK_LEGACY_SWITCH_USER_NAME_EN = ["Switch", "user"].join(" ");
    const GROK_LEGACY_SWITCH_USER_SELECTOR = ["#", "floatingBall"].join("");
    const GROK_ADMIN_ICON = svgDataUrlLocal(`
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" role="img">
            <path d="M12 3l7 3v5c0 4.5-3 8.5-7 10-4-1.5-7-5.5-7-10V6l7-3z"></path>
            <path d="M9 12l2 2 4-4"></path>
        </svg>
    `);
    const defaultIconURL = "https://grok.com/images/favicon-light.png";
    const defaultIcons = [
      { name: "Grok", url: "https://grok.com/images/favicon-light.png" },
      { name: "Grok Dark", url: "https://grok.com/images/favicon-dark.png" },
      { name: "Google", url: "https://www.google.com/favicon.ico" },
      { name: "Bing", url: "https://www.bing.com/favicon.ico" },
      { name: "DuckDuckGo", url: "https://duckduckgo.com/favicon.ico" },
      { name: "Baidu", url: "https://www.baidu.com/favicon.ico" },
      { name: "Wikipedia", url: "https://www.wikipedia.org/static/favicon/wikipedia.ico" },
      { name: "Reddit", url: "https://www.reddit.com/favicon.ico" },
      { name: "Stack Overflow", url: "https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico" },
      { name: "GitHub", url: "https://github.githubassets.com/favicons/favicon.svg" },
      { name: "Twitter / X", url: "https://abs.twimg.com/favicons/twitter.3.ico" },
      { name: "Bilibili", url: "https://www.bilibili.com/favicon.ico" },
      { name: "YouTube", url: "https://www.youtube.com/favicon.ico" }
    ];
    const protectedIconUrls = [
      "https://grok.com/images/favicon-light.png",
      "https://grok.com/images/favicon-dark.png"
    ];
    const SITE_MESSAGES = Object.freeze({
      "zh-CN": {
        menuCommandLabel: "Grok - 设置快捷键",
        panelTitle: "Grok - 自定义快捷键",
        keepSidebarVisibleLabel: "Grok - 保持侧边栏显示: {state}",
        on: "开",
        off: "关",
        shortcuts: {
          "Admin": "Admin",
          "Private": "私密模式",
          "New Chat": "新建聊天",
          "Sidebar": "侧边栏",
          "Project": "项目"
        }
      },
      "en-US": {
        menuCommandLabel: "Grok - Shortcut settings",
        panelTitle: "Grok - Custom shortcuts",
        keepSidebarVisibleLabel: "Grok - Keep sidebar visible: {state}",
        on: "On",
        off: "Off",
        shortcuts: {
          "Admin": "Admin"
        }
      }
    });
    const SELECTORS = Object.freeze({
      sidebarToggle: 'button[data-sidebar="trigger"][type="button"]',
      sidebarProvider: '[data-variant="sidebar"][data-side]',
      sidebarRoot: '[data-sidebar="sidebar"]'
    });
    const GROK_SHORTCUTS_STORAGE_KEY = "grok_shortcuts";
    const SIDEBAR_VISIBILITY_STORAGE_KEY = "grok_keep_sidebar_visible_v1";
    const DEFAULT_KEEP_SIDEBAR_VISIBLE = true;
    const SIDEBAR_AUTO_EXPAND_MAX_VIEWPORT_WIDTH = 1024;
    const SIDEBAR_OPEN_SELECTORS = [
      `${SELECTORS.sidebarProvider}[data-state="expanded"]`,
      `${SELECTORS.sidebarProvider}[data-state="open"]`,
      `${SELECTORS.sidebarProvider}[data-state="opened"]`,
      `${SELECTORS.sidebarProvider}[aria-expanded="true"]`
    ];
    const SIDEBAR_CLOSED_SELECTORS = [
      `${SELECTORS.sidebarProvider}[data-state="collapsed"]`,
      `${SELECTORS.sidebarProvider}[data-state="closed"]`,
      `${SELECTORS.sidebarProvider}[data-state="close"]`,
      `${SELECTORS.sidebarProvider}[aria-expanded="false"]`,
      `${SELECTORS.sidebarProvider}[data-collapsible="offcanvas"]`,
      `${SELECTORS.sidebarProvider}[data-collapsible="icon"]`
    ];
    let keepSidebarVisible = getKeepSidebarVisibleSetting();
    let sidebarVisibilityMenuCommandId = null;
    let sidebarWarmupTimer = null;
    const defaultShortcuts = [
      {
        key: "admin",
        labelKey: "shortcuts.Admin",
        name: "Admin",
        actionType: "url",
        selector: "",
        url: GROK_ADMIN_URL,
        urlMethod: "current",
        urlAdvanced: "href",
        simulateKeys: "",
        hotkey: "CTRL+U",
        icon: GROK_ADMIN_ICON,
        iconAdaptive: true
      },
      {
        name: "Private",
        actionType: "selector",
        selector: 'a[aria-label*="Switch to "]',
        url: "",
        urlMethod: "current",
        urlAdvanced: "href",
        simulateKeys: "",
        hotkey: "CTRL+I",
        icon: "data:image/svg+xml,%3Csvg%20width%3D%2220%22%20height%3D%2220%22%20viewBox%3D%220%200%2024%2024%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20class%3D%22stroke-%5B2%5D%20%22%20stroke-width%3D%222%22%20data-testid%3D%22pi-ghost%22%3E%3Cellipse%20cx%3D%2210%22%20cy%3D%2210.25%22%20rx%3D%221.25%22%20ry%3D%221.75%22%20fill%3D%22currentColor%22%3E%3C%2Fellipse%3E%3Cellipse%20cx%3D%2214%22%20cy%3D%2210.25%22%20rx%3D%221.25%22%20ry%3D%221.75%22%20fill%3D%22currentColor%22%3E%3C%2Fellipse%3E%3Cpath%20d%3D%22M12%204C4%204%208.07627%2010.7212%203%2013C3%2014.6491%204.40343%2014.5%204.93%2015.77C5.37046%2016.8323%204.27588%2018.9597%204%2020H8L12%2021L16%2020H20C19.6222%2018.7198%2018.8092%2017.1437%2019.075%2015.7742C19.3479%2014.3681%2021%2014.742%2021%2013C15.9237%2010.7212%2020%204%2012%204Z%22%20stroke%3D%22currentColor%22%3E%3C%2Fpath%3E%3C%2Fsvg%3E",
        iconAdaptive: true
      },
      {
        name: "New Chat",
        actionType: "selector",
        selector: '[aria-label="Home page"]',
        url: "",
        urlMethod: "current",
        urlAdvanced: "href",
        simulateKeys: "",
        hotkey: "CTRL+N",
        icon: "data:image/svg+xml,%3Csvg%20width%3D%2218%22%20height%3D%2218%22%20viewBox%3D%220%200%2024%2024%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20class%3D%22stroke-%5B2%5D%20%22%3E%3Cpath%20d%3D%22M10%204V4C8.13623%204%207.20435%204%206.46927%204.30448C5.48915%204.71046%204.71046%205.48915%204.30448%206.46927C4%207.20435%204%208.13623%204%2010V13.6C4%2015.8402%204%2016.9603%204.43597%2017.816C4.81947%2018.5686%205.43139%2019.1805%206.18404%2019.564C7.03968%2020%208.15979%2020%2010.4%2020H14C15.8638%2020%2016.7956%2020%2017.5307%2019.6955C18.5108%2019.2895%2019.2895%2018.5108%2019.6955%2017.5307C20%2016.7956%2020%2015.8638%2020%2014V14%22%20stroke%3D%22currentColor%22%20stroke-linecap%3D%22square%22%3E%3C%2Fpath%3E%3Cpath%20d%3D%22M12.4393%2014.5607L19.5%207.5C20.3284%206.67157%2020.3284%205.32843%2019.5%204.5C18.6716%203.67157%2017.3284%203.67157%2016.5%204.5L9.43934%2011.5607C9.15804%2011.842%209%2012.2235%209%2012.6213V15H11.3787C11.7765%2015%2012.158%2014.842%2012.4393%2014.5607Z%22%20stroke%3D%22currentColor%22%20stroke-linecap%3D%22square%22%3E%3C%2Fpath%3E%3C%2Fsvg%3E",
        iconAdaptive: true
      },
      {
        name: "Sidebar",
        actionType: "selector",
        selector: SELECTORS.sidebarToggle,
        url: "",
        urlMethod: "current",
        urlAdvanced: "href",
        simulateKeys: "",
        hotkey: "CTRL+B",
        icon: "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218%22%20height%3D%2218%22%20viewBox%3D%220%200%2024%2024%22%20fill%3D%22none%22%20stroke%3D%22currentColor%22%20stroke-width%3D%222%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%20class%3D%22lucide%20lucide-chevrons-right%20rotate-180%20transition-transform%20duration-200%22%3E%3Cpath%20d%3D%22m6%2017%205-5-5-5%22%3E%3C%2Fpath%3E%3Cpath%20d%3D%22m13%2017%205-5-5-5%22%3E%3C%2Fpath%3E%3C%2Fsvg%3E",
        iconAdaptive: true
      },
      {
        name: "Project",
        actionType: "url",
        url: "https://grok.com/project",
        urlMethod: "current",
        urlAdvanced: "href",
        selector: "",
        simulateKeys: "",
        hotkey: "CTRL+P",
        icon: "data:image/svg+xml,%3Csvg%20width%3D%2218%22%20height%3D%2218%22%20viewBox%3D%22-1%20-1%2025%2025%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20class%3D%22stroke-%5B2%5D%20%22%3E%3Cpath%20d%3D%22M3.33965%2017L11.9999%2022L20.6602%2017V7L11.9999%202L3.33965%207V17Z%22%20stroke%3D%22currentColor%22%3E%3C%2Fpath%3E%3Cpath%20d%3D%22M11.9999%2012L3.4999%207M11.9999%2012L12%2021.5M11.9999%2012L20.5%207%22%20stroke%3D%22currentColor%22%3E%3C%2Fpath%3E%3C%2Fsvg%3E",
        iconAdaptive: true
      }
    ];
    const GROK_ADMIN_SHORTCUT_TEMPLATE = defaultShortcuts[0] || null;
    function cloneGrokShortcutRecord(shortcut) {
      if (!shortcut || typeof shortcut !== "object" || Array.isArray(shortcut)) return null;
      const next = { ...shortcut };
      if (shortcut.data && typeof shortcut.data === "object" && !Array.isArray(shortcut.data)) {
        next.data = { ...shortcut.data };
      }
      return next;
    }
    function isLegacySwitchUserShortcut(shortcut) {
      const name = String(shortcut?.name || "").trim();
      const selector = String(shortcut?.selector || "").trim();
      const actionType = String(shortcut?.actionType || "").trim();
      return name === GROK_LEGACY_SWITCH_USER_NAME_ZH || name === GROK_LEGACY_SWITCH_USER_NAME_EN || actionType === "selector" && selector === GROK_LEGACY_SWITCH_USER_SELECTOR;
    }
    function isGrokDefaultShortcutRecord(shortcut) {
      const name = String(shortcut?.name || "").trim();
      if (!name) return false;
      if (name === "Admin") return true;
      if (name === "Private") return true;
      if (name === "New Chat") return true;
      if (name === "Sidebar") return true;
      if (name === "Project") return true;
      const labelKey = String(shortcut?.labelKey || "").trim();
      if (labelKey === "shortcuts.Admin") return true;
      if (labelKey === "shortcuts.Private") return true;
      if (labelKey === "shortcuts.New Chat") return true;
      if (labelKey === "shortcuts.Sidebar") return true;
      if (labelKey === "shortcuts.Project") return true;
      const actionType = String(shortcut?.actionType || "").trim();
      const selector = String(shortcut?.selector || "").trim();
      const url = String(shortcut?.url || "").trim();
      if (name === "Private" && actionType === "selector" && selector === 'a[aria-label*="Switch to "]') return true;
      if (name === "New Chat" && actionType === "selector" && selector === '[aria-label="Home page"]') return true;
      if (name === "Sidebar" && actionType === "selector" && selector === SELECTORS.sidebarToggle) return true;
      if (name === "Project" && actionType === "url" && url === "https://grok.com/project") return true;
      if (name === "Admin" && actionType === "url" && url === GROK_ADMIN_URL) return true;
      return false;
    }
    function migrateGrokShortcuts() {
      const stored = gmGetValueLocal(GROK_SHORTCUTS_STORAGE_KEY, null);
      if (!Array.isArray(stored)) return;
      let changed = false;
      const next = stored.map((shortcut) => {
        const cloned = cloneGrokShortcutRecord(shortcut);
        if (!cloned) return shortcut;
        if (isLegacySwitchUserShortcut(cloned)) {
          const replacement = cloneGrokShortcutRecord(GROK_ADMIN_SHORTCUT_TEMPLATE) || {};
          changed = true;
          return {
            ...replacement,
            id: cloned.id || replacement.id || "",
            iconAdaptive: true
          };
        }
        if (isGrokDefaultShortcutRecord(cloned) && cloned.iconAdaptive !== true) {
          cloned.iconAdaptive = true;
          changed = true;
        }
        return cloned;
      });
      if (!changed) return;
      gmSetValueLocal(GROK_SHORTCUTS_STORAGE_KEY, next);
    }
    function getLocalBooleanFallback(key, fallback) {
      const storage = getLocalStorageLocal();
      const normalizedKey = String(key ?? "").trim();
      if (!storage || !normalizedKey) return fallback;
      try {
        const raw = storage.getItem(normalizedKey);
        if (raw == null) return fallback;
        if (raw === "true" || raw === "1") return true;
        if (raw === "false" || raw === "0") return false;
        const parsed = JSON.parse(raw);
        if (typeof parsed === "boolean") return parsed;
      } catch {
      }
      return fallback;
    }
    function setLocalBooleanFallback(key, value) {
      const storage = getLocalStorageLocal();
      const normalizedKey = String(key ?? "").trim();
      if (!storage || !normalizedKey) return;
      try {
        storage.setItem(normalizedKey, JSON.stringify(!!value));
      } catch {
      }
    }
    function getKeepSidebarVisibleSetting() {
      const localFallback = getLocalBooleanFallback(SIDEBAR_VISIBILITY_STORAGE_KEY, DEFAULT_KEEP_SIDEBAR_VISIBLE);
      try {
        const value = gmGetValueLocal(SIDEBAR_VISIBILITY_STORAGE_KEY, DEFAULT_KEEP_SIDEBAR_VISIBLE);
        if (value && typeof value.then === "function") return localFallback;
        return value === true || value === "true";
      } catch {
      }
      return localFallback;
    }
    function setKeepSidebarVisibleSetting(value) {
      try {
        gmSetValueLocal(SIDEBAR_VISIBILITY_STORAGE_KEY, !!value);
      } catch {
      }
      setLocalBooleanFallback(SIDEBAR_VISIBILITY_STORAGE_KEY, !!value);
    }
    function getSidebarVisibilityMenuLabel() {
      const stateText = engine?.i18n?.t?.(keepSidebarVisible ? "on" : "off", {}, keepSidebarVisible ? "On" : "Off") || (keepSidebarVisible ? "On" : "Off");
      return engine?.i18n?.t?.("keepSidebarVisibleLabel", { state: stateText }, `Grok - Keep sidebar visible: ${stateText}`) || `Grok - Keep sidebar visible: ${stateText}`;
    }
    function registerSidebarVisibilityMenuCommand() {
      if (sidebarVisibilityMenuCommandId !== null) {
        try {
          gmUnregisterMenuCommandLocal(sidebarVisibilityMenuCommandId);
        } catch {
        }
      }
      sidebarVisibilityMenuCommandId = gmRegisterMenuCommandLocal(getSidebarVisibilityMenuLabel(), () => {
        setSidebarVisibilityPreference(!keepSidebarVisible);
      });
    }
    function isElementVisible(el) {
      if (!el) return false;
      if (el.offsetParent !== null) return true;
      try {
        const rect = el.getBoundingClientRect?.();
        return !!rect && rect.width > 0 && rect.height > 0;
      } catch {
        return false;
      }
    }
    function getFirstVisibleBySelector(selector, { fallbackToFirst = false } = {}) {
      if (typeof selector !== "string" || !selector.trim()) return null;
      let all = [];
      try {
        all = Array.from(document.querySelectorAll(selector));
      } catch {
        return null;
      }
      for (const el of all) {
        if (isElementVisible(el)) return el;
      }
      return fallbackToFirst ? all[0] || null : null;
    }
    function getSidebarToggleButton() {
      return getFirstVisibleBySelector(SELECTORS.sidebarToggle, { fallbackToFirst: true });
    }
    function getSidebarProviderElement(fromElement = null) {
      const directProvider = fromElement?.closest?.(SELECTORS.sidebarProvider);
      if (directProvider) return directProvider;
      const sidebarRoot = fromElement?.closest?.(SELECTORS.sidebarRoot) || getFirstVisibleBySelector(SELECTORS.sidebarRoot, { fallbackToFirst: true });
      const providerFromRoot = sidebarRoot?.closest?.(SELECTORS.sidebarProvider);
      if (providerFromRoot) return providerFromRoot;
      return getFirstVisibleBySelector(SELECTORS.sidebarProvider, { fallbackToFirst: true });
    }
    function parseBooleanAttr(value) {
      const token = String(value ?? "").trim().toLowerCase();
      if (token === "true") return true;
      if (token === "false") return false;
      return null;
    }
    function inferSidebarStateFromClassName(value) {
      const token = String(value ?? "").toLowerCase();
      if (!token) return null;
      if (/(sidebar|sidenav)[-_a-z0-9]*(collapsed|closed|hidden)/.test(token)) return false;
      if (/(sidebar|sidenav)[-_a-z0-9]*(expanded|opened|open|visible)/.test(token)) return true;
      return null;
    }
    function readSidebarStateFromElement(element) {
      if (!element) return null;
      const isSidebarTrigger = element.matches?.(SELECTORS.sidebarToggle) || String(element.getAttribute?.("data-sidebar") || "").trim().toLowerCase() === "trigger";
      const expanded = parseBooleanAttr(element.getAttribute?.("aria-expanded"));
      if (expanded !== null) return expanded;
      const hidden = parseBooleanAttr(element.getAttribute?.("aria-hidden"));
      if (hidden !== null) return !hidden;
      if (!isSidebarTrigger) {
        const stateAttr = String(element.getAttribute?.("data-state") || "").trim().toLowerCase();
        if (stateAttr === "expanded" || stateAttr === "open" || stateAttr === "opened") return true;
        if (stateAttr === "collapsed" || stateAttr === "close" || stateAttr === "closed") return false;
        const collapsibleAttr = String(element.getAttribute?.("data-collapsible") || "").trim().toLowerCase();
        if (collapsibleAttr === "offcanvas" || collapsibleAttr === "icon") return false;
      }
      return inferSidebarStateFromClassName(element.className || "");
    }
    function readSidebarStateFromToggle(button) {
      if (!button) return null;
      const provider = getSidebarProviderElement(button);
      const providerState = readSidebarStateFromElement(provider);
      if (providerState !== null) return providerState;
      const directExpanded = parseBooleanAttr(button.getAttribute?.("aria-expanded"));
      if (directExpanded !== null) return directExpanded;
      const directPressed = parseBooleanAttr(button.getAttribute?.("aria-pressed"));
      if (directPressed !== null) return directPressed;
      const ariaLabel = String(button.getAttribute?.("aria-label") || "").trim().toLowerCase();
      if (/(open|expand|show).*(menu|navigation|sidebar|side nav|panel)/.test(ariaLabel)) return false;
      if (/(close|collapse|hide).*(menu|navigation|sidebar|side nav|panel)/.test(ariaLabel)) return true;
      const controlsId = String(button.getAttribute?.("aria-controls") || "").trim();
      if (controlsId) {
        const controlled = document.getElementById(controlsId);
        const controlledState = readSidebarStateFromElement(getSidebarProviderElement(controlled) || controlled);
        if (controlledState !== null) return controlledState;
      }
      const host = button.closest?.(`${SELECTORS.sidebarRoot}, [data-sidebar="rail"], [class*="sidebar"], [class*="sidenav"]`);
      return readSidebarStateFromElement(getSidebarProviderElement(host) || host);
    }
    function isSidebarOpen() {
      const sidebarProvider = getSidebarProviderElement();
      const providerState = readSidebarStateFromElement(sidebarProvider);
      if (providerState !== null) return providerState;
      const sidebarRoot = getFirstVisibleBySelector(SELECTORS.sidebarRoot, { fallbackToFirst: true });
      const rootState = readSidebarStateFromElement(sidebarRoot);
      if (rootState !== null) return rootState;
      for (const selector of SIDEBAR_OPEN_SELECTORS) {
        const el = getFirstVisibleBySelector(selector);
        if (el) return true;
      }
      for (const selector of SIDEBAR_CLOSED_SELECTORS) {
        const el = getFirstVisibleBySelector(selector, { fallbackToFirst: true });
        if (el) return false;
      }
      const button = getSidebarToggleButton();
      const fromToggle = readSidebarStateFromToggle(button);
      if (fromToggle !== null) return fromToggle;
      return null;
    }
    function clickSidebarToggleButton() {
      const button = getSidebarToggleButton();
      if (!button) return false;
      try {
        const clicked = TemplateUtils?.events?.simulateClick?.(button, { nativeFallback: true });
        if (clicked) return true;
      } catch {
      }
      try {
        button.click();
        return true;
      } catch {
      }
      return false;
    }
    function getViewportWidth() {
      const width = Number(window.innerWidth) || Number(document.documentElement?.clientWidth) || 0;
      return width > 0 ? width : 0;
    }
    function isSidebarAutoExpandSuppressedByViewport() {
      const width = getViewportWidth();
      return width > 0 && width <= SIDEBAR_AUTO_EXPAND_MAX_VIEWPORT_WIDTH;
    }
    function shouldWarmupSidebarInBackground() {
      return keepSidebarVisible && !isSidebarAutoExpandSuppressedByViewport();
    }
    function ensureSidebarVisible() {
      if (!keepSidebarVisible) return false;
      const open = isSidebarOpen();
      if (open === true) return true;
      if (open === false) return clickSidebarToggleButton();
      return false;
    }
    function stopSidebarWarmup() {
      if (sidebarWarmupTimer === null) return;
      try {
        clearInterval(sidebarWarmupTimer);
      } catch {
      }
      sidebarWarmupTimer = null;
    }
    function startSidebarWarmup({ attempts = 20, intervalMs = 500 } = {}) {
      stopSidebarWarmup();
      if (!shouldWarmupSidebarInBackground()) return;
      let remaining = Math.max(1, Number(attempts) || 1);
      const interval = Math.max(150, Number(intervalMs) || 500);
      const tick = () => {
        if (!shouldWarmupSidebarInBackground()) {
          stopSidebarWarmup();
          return;
        }
        const open = isSidebarOpen();
        if (open === true) {
          stopSidebarWarmup();
          return;
        }
        ensureSidebarVisible();
        remaining -= 1;
        if (remaining <= 0) stopSidebarWarmup();
      };
      tick();
      sidebarWarmupTimer = window.setInterval(tick, interval);
    }
    function setSidebarVisibilityPreference(nextValue) {
      keepSidebarVisible = !!nextValue;
      setKeepSidebarVisibleSetting(keepSidebarVisible);
      if (keepSidebarVisible) {
        if (shouldWarmupSidebarInBackground()) {
          startSidebarWarmup();
        } else {
          stopSidebarWarmup();
        }
      } else {
        stopSidebarWarmup();
      }
      console.info(`${LOG_TAG} keep sidebar visible is now ${keepSidebarVisible ? "enabled" : "disabled"}.`);
      registerSidebarVisibilityMenuCommand();
      return keepSidebarVisible;
    }
    function setupKeepSidebarVisible() {
      let wasSidebarAutoExpandSuppressed = isSidebarAutoExpandSuppressedByViewport();
      window.addEventListener("load", () => {
        setTimeout(() => startSidebarWarmup(), 650);
      }, { once: true });
      if (document.readyState === "complete") {
        setTimeout(() => startSidebarWarmup(), 800);
      }
      let lastUrl = location.href;
      const observer = new MutationObserver(() => {
        const currentUrl = location.href;
        if (currentUrl !== lastUrl) {
          lastUrl = currentUrl;
          startSidebarWarmup();
        }
      });
      observer.observe(document.documentElement || document, { subtree: true, childList: true });
      document.addEventListener("visibilitychange", () => {
        if (document.visibilityState === "visible") startSidebarWarmup();
      });
      window.addEventListener("resize", () => {
        const suppressed = isSidebarAutoExpandSuppressedByViewport();
        if (suppressed === wasSidebarAutoExpandSuppressed) return;
        wasSidebarAutoExpandSuppressed = suppressed;
        if (suppressed) {
          stopSidebarWarmup();
          return;
        }
        if (keepSidebarVisible) startSidebarWarmup();
      });
    }
    migrateGrokShortcuts();
    const engine = ShortcutTemplate.createShortcutEngine({
      // 基本配置
      menuCommandLabel: "Grok - 设置快捷键",
      panelTitle: "Grok - 自定义快捷键",
      // 存储配置（保持与原脚本一致）
      storageKeys: {
        shortcuts: GROK_SHORTCUTS_STORAGE_KEY,
        iconCachePrefix: "grok_icon_cache_v1::",
        userIcons: "grok_user_icons_v1"
      },
      // UI 配置
      ui: {
        idPrefix: "grok",
        cssPrefix: "grok",
        compactBreakpoint: 800
      },
      i18n: {
        messages: SITE_MESSAGES
      },
      // 图标配置
      defaultIconURL,
      iconLibrary: defaultIcons,
      protectedIconUrls,
      // 默认快捷键
      defaultShortcuts,
      // 主题颜色（Grok主题色）
      colors: {
        primary: "#5D5CDE"
      },
      // 日志标签
      consoleTag: LOG_TAG,
      // 图标缓存绕过规则（对Grok图标不使用缓存）
      shouldBypassIconCache: (url) => {
        return url && url.startsWith("https://grok.com/");
      },
      // 智能导航配置（支持SPA路由）
      resolveUrlTemplate: (targetUrl, { getCurrentSearchTerm, placeholderToken }) => {
        return targetUrl;
      },
      // 文本配置
      text: {
        stats: {
          total: "总计",
          url: "URL跳转",
          selector: "元素点击",
          simulate: "按键模拟"
        },
        buttons: {
          addShortcut: "添加新快捷键",
          saveAndClose: "保存并关闭",
          confirm: "确定",
          cancel: "取消",
          delete: "删除",
          edit: "编辑",
          clear: "清除"
        },
        dialogs: {
          alert: "提示",
          confirm: "确认",
          prompt: "输入"
        },
        hints: {
          hotkey: "点击此处，然后按下快捷键组合",
          simulate: "点击此处，然后按下要模拟的按键组合",
          hotkeyHelp: "💡 支持 Ctrl/Shift/Alt/Cmd + 字母/数字/功能键等组合",
          simulateHelp: "⚡ 将模拟这个按键组合发送到网页"
        }
      }
    });
    engine.init();
    setupKeepSidebarVisible();
    registerSidebarVisibilityMenuCommand();
  })();
})();
