// ==UserScript==
// @name         [Le Chat] 快捷键跳转 [20260423] v1.0.0
// @namespace    0_V userscripts/[Le Chat] 快捷键跳转
// @description  为 Le Chat 添加自定义快捷键，依托通用模板实现快捷面板、图标库、统计筛选、暗黑模式、自适应布局、事件隔离、快捷键捕获等功能。

// @version      [20260423] v1.0.0
// @update-log   1.0.0: 修正站点脚本 @resource 地址，统一改为 release 分支 raw ESM 资源，避免继续引用本地相对路径。

// @match        https://chat.mistral.ai/*

// @grant        GM_registerMenuCommand
// @grant        GM_getValue
// @grant        GM_setValue
// @grant        GM_xmlhttpRequest
// @grant        GM_getResourceURL

// @connect      *

// @icon         https://github.com/0-V-linuxdo/Template_shortcuts.js/raw/refs/heads/release/Site_Icon/Le_Chat_keycap.svg
// @resource     template-core https://github.com/0-V-linuxdo/Template_shortcuts.js/raw/refs/heads/release/dist/esm/template-core.js
// @resource     site-entry https://github.com/0-V-linuxdo/Template_shortcuts.js/raw/refs/heads/release/dist/esm/sites/le-chat.js
// ==/UserScript==

/* ===================== IMPORTANT · NOTICE · START =====================
 *
 * 1. [编辑指引 | Edit Guidance]
 *    • ⚠️ 这是一个自动生成的文件：请不要直接修改当前产物。
 *    • ⚠️ 源码真源位于当前仓库 `main` 分支的 `src/modules/` 与 `src/sites/`；userscript bootstrap 模板位于 `src/userscript/entry.js`；站点元数据位于 `src/sites/manifest.js`；Template 归档头部元数据位于 `src/userscript/header.txt`。
 *    • ⚠️ 在 `main` 分支运行 `npm run build` 会刷新本地 `dist/esm/`、`Site_JS/` 与 `archive/Template_JS/[Template] shortcut core.js`。
 *    • ⚠️ 最新发布物应同步到当前仓库的 `release` 分支；`archive/` 仅保存历史归档与参考资料，不参与当前 userscript 运行时加载。
 *    • ⚠️ This is a generated artifact. Do not edit this file directly. The source of truth lives in the current repository's `main` branch under `src/modules/`, `src/sites/`, `src/userscript/entry.js`, `src/sites/manifest.js`, and `src/userscript/header.txt`. Run `npm run build` on `main` to refresh local outputs, then stage release assets for the repository's `release` branch.
 *
 * ----------------------------------------------------------------------
 *
 * 2. [安全提示 | Safety Reminder]
 *    • ✅ 必须使用 `setTrustedHTML`，不得使用 `innerHTML`。
 *    • ✅ Always call `setTrustedHTML`; never rely on `innerHTML`.
 *
 * ====================== IMPORTANT · NOTICE · END ======================
 */

(() => {
    'use strict';

    const SITE_ID = "le-chat";
    const SITE_LABEL = "[Le Chat] 快捷键跳转";
    const RESOURCE_NAMES = Object.freeze({
    "core": "template-core",
    "site": "site-entry"
});
    const BOOTSTRAP_MENU_COMMANDS = Object.freeze([]);
    const MENU_MESSAGE_SOURCE = "template-shortcuts-userscript";
    const MENU_PENDING_VALUE_KEY = "__templateShortcutsMenuPendingValue::le-chat";
    const MENU_PAGE_TOKEN = Date.now().toString(36) + '_' + Math.random().toString(36).slice(2, 10);
    const MENU_COMMAND_MAX_AGE_MS = 5 * 60 * 1000;

    function getGlobalScope() {
        return typeof globalThis !== 'undefined' ? globalThis : null;
    }

    function getDirectUserscriptApi(name) {
        switch (String(name || "")) {
            case 'GM_getValue':
                return typeof GM_getValue === 'function' ? GM_getValue : null;
            case 'GM_setValue':
                return typeof GM_setValue === 'function' ? GM_setValue : null;
            case 'GM_addValueChangeListener':
                return typeof GM_addValueChangeListener === 'function' ? GM_addValueChangeListener : null;
            case 'GM_removeValueChangeListener':
                return typeof GM_removeValueChangeListener === 'function' ? GM_removeValueChangeListener : null;
            case 'GM_xmlhttpRequest':
                return typeof GM_xmlhttpRequest === 'function' ? GM_xmlhttpRequest : null;
            case 'GM_getResourceURL':
                return typeof GM_getResourceURL === 'function' ? GM_getResourceURL : null;
            case 'GM_registerMenuCommand':
                return typeof GM_registerMenuCommand === 'function' ? GM_registerMenuCommand : null;
            case 'GM_unregisterMenuCommand':
                return typeof GM_unregisterMenuCommand === 'function' ? GM_unregisterMenuCommand : null;
            default:
                return null;
        }
    }

    function getUserscriptApi(name) {
        const directBinding = getDirectUserscriptApi(name);
        if (typeof directBinding === 'function') return directBinding;

        const scope = getGlobalScope();
        if (!scope) return null;

        const direct = scope[name];
        if (typeof direct === 'function') return direct.bind(scope);

        const gm = scope.GM;
        if (gm && typeof gm === 'object') {
            const altName = name.replace(/^GM_/, '');
            const directGm = gm[altName];
            if (typeof directGm === 'function') return directGm.bind(gm);

            const lowerCamel = altName.charAt(0).toLowerCase() + altName.slice(1);
            const camelGm = gm[lowerCamel];
            if (typeof camelGm === 'function') return camelGm.bind(gm);
        }

        return null;
    }

    function gmGetValueSafe(key, fallback) {
        const fn = getUserscriptApi('GM_getValue');
        if (typeof fn !== 'function') return fallback;
        try {
            const value = fn(key, fallback);
            return value === undefined ? fallback : value;
        } catch {
            return fallback;
        }
    }

    function gmSetValueSafe(key, value) {
        const fn = getUserscriptApi('GM_setValue');
        if (typeof fn !== 'function') return false;
        try {
            fn(key, value);
            return true;
        } catch {
            return false;
        }
    }

    function exposeUserscriptApiResolver() {
        const scope = getGlobalScope();
        if (!scope) return;

        try {
            Object.defineProperty(scope, "__TEMPLATE_SHORTCUTS_GET_USERSCRIPT_API__", {
                value: getUserscriptApi,
                configurable: true,
                enumerable: false,
                writable: true
            });
            return;
        } catch {}

        try {
            scope["__TEMPLATE_SHORTCUTS_GET_USERSCRIPT_API__"] = getUserscriptApi;
        } catch {}
    }

    function createMenuBridge() {
        const register = getUserscriptApi('GM_registerMenuCommand');
        const unregister = getUserscriptApi('GM_unregisterMenuCommand');
        const addValueChangeListener = getUserscriptApi('GM_addValueChangeListener');
        const removeValueChangeListener = getUserscriptApi('GM_removeValueChangeListener');
        let settingsHandler = null;
        const commands = new Map();
        const commandConfigs = new Map();
        const commandStateListenerIds = new Map();
        const scope = getGlobalScope();
        const dispatchTarget = scope?.document && typeof scope.document.dispatchEvent === 'function'
            ? scope.document
            : (scope && typeof scope.dispatchEvent === 'function' ? scope : null);

        function normalizeCommandKey(commandKey) {
            return String(commandKey || "").trim();
        }

        function createCommandId(commandKey) {
            const key = normalizeCommandKey(commandKey) || 'menu';
            return key + ':' + Date.now().toString(36) + ':' + Math.random().toString(36).slice(2, 10);
        }

        function normalizeBooleanState(value, fallback = false) {
            if (value === true || value === "true" || value === 1 || value === "1") return true;
            if (value === false || value === "false" || value === 0 || value === "0") return false;
            return !!fallback;
        }

        function buildCommandConfig(commandKey, label) {
            const source = (commandKey && typeof commandKey === 'object' && !Array.isArray(commandKey))
                ? commandKey
                : { key: commandKey, label };
            const key = normalizeCommandKey(source?.key);
            if (!key) return null;

            const previous = commandConfigs.get(key) || null;
            const directLabel = typeof source?.label === 'string' && source.label.trim()
                ? source.label.trim()
                : (typeof previous?.label === 'string' ? previous.label : '');
            const stateKey = typeof source?.stateKey === 'string' && source.stateKey.trim()
                ? source.stateKey.trim()
                : (typeof previous?.stateKey === 'string' ? previous.stateKey : '');
            const labelOn = typeof source?.labelOn === 'string' && source.labelOn.trim()
                ? source.labelOn.trim()
                : (typeof previous?.labelOn === 'string' ? previous.labelOn : '');
            const labelOff = typeof source?.labelOff === 'string' && source.labelOff.trim()
                ? source.labelOff.trim()
                : (typeof previous?.labelOff === 'string' ? previous.labelOff : '');
            const hasBooleanStateLabel = !!stateKey && !!labelOn && !!labelOff;
            const resolvedLabel = directLabel || (hasBooleanStateLabel ? labelOn : '');
            if (!resolvedLabel) return null;

            return Object.freeze({
                key,
                label: resolvedLabel,
                stateKey: hasBooleanStateLabel ? stateKey : '',
                stateDefault: hasBooleanStateLabel
                    ? (typeof source?.stateDefault === 'boolean'
                        ? source.stateDefault
                        : (previous?.stateDefault === true))
                    : false,
                labelOn: hasBooleanStateLabel ? labelOn : '',
                labelOff: hasBooleanStateLabel ? labelOff : ''
            });
        }

        function isStatefulCommand(config) {
            return !!config?.stateKey && !!config?.labelOn && !!config?.labelOff;
        }

        function resolveCommandLabel(config) {
            if (!isStatefulCommand(config)) {
                return typeof config?.label === 'string' ? config.label : '';
            }
            const state = normalizeBooleanState(gmGetValueSafe(config.stateKey, config.stateDefault), config.stateDefault);
            return state ? config.labelOn : config.labelOff;
        }

        function refreshCommandLabel(commandKey, delay = 450) {
            const key = normalizeCommandKey(commandKey);
            if (!key) return;
            const schedule = scope && typeof scope.setTimeout === 'function' ? scope.setTimeout.bind(scope) : setTimeout;
            try {
                schedule(() => {
                    try { registerCommand(key); } catch {}
                }, Math.max(0, Number(delay) || 0));
            } catch {}
        }

        function bindCommandStateListener(config) {
            if (!isStatefulCommand(config)) return;
            if (typeof addValueChangeListener !== 'function') return;
            if (commandStateListenerIds.has(config.key)) return;
            try {
                const listenerId = addValueChangeListener(config.stateKey, () => {
                    refreshCommandLabel(config.key, 0);
                });
                if (listenerId !== null && listenerId !== undefined) {
                    commandStateListenerIds.set(config.key, listenerId);
                }
            } catch {}
        }

        function unbindCommandStateListener(commandKey) {
            const key = normalizeCommandKey(commandKey);
            if (!key) return;
            const listenerId = commandStateListenerIds.get(key);
            if (listenerId === undefined) return;
            commandStateListenerIds.delete(key);
            if (typeof removeValueChangeListener !== 'function') return;
            try { removeValueChangeListener(listenerId); } catch {}
        }

        function normalizePendingEntries(entries) {
            const now = Date.now();
            const normalized = [];
            const seenIds = new Set();

            for (const entry of Array.isArray(entries) ? entries : []) {
                const id = typeof entry?.id === 'string' ? entry.id.trim() : '';
                const key = normalizeCommandKey(entry?.key);
                const pageToken = typeof entry?.pageToken === 'string' ? entry.pageToken.trim() : '';
                const createdAt = Number(entry?.createdAt);
                if (!id || !key || !pageToken) continue;
                if (!Number.isFinite(createdAt)) continue;
                if ((now - createdAt) > MENU_COMMAND_MAX_AGE_MS) continue;
                if (seenIds.has(id)) continue;
                seenIds.add(id);
                normalized.push(Object.freeze({ id, key, pageToken, createdAt }));
            }

            if (normalized.length <= 48) return normalized;
            return normalized.slice(normalized.length - 48);
        }

        function readPendingEntries() {
            return normalizePendingEntries(gmGetValueSafe(MENU_PENDING_VALUE_KEY, []));
        }

        function writePendingEntries(entries) {
            return gmSetValueSafe(MENU_PENDING_VALUE_KEY, normalizePendingEntries(entries));
        }

        function queuePendingCommand(commandKey, commandId) {
            const key = normalizeCommandKey(commandKey);
            const id = String(commandId || "").trim() || createCommandId(key);
            if (!key || !id) return null;
            const pendingEntries = readPendingEntries();
            pendingEntries.push(Object.freeze({
                id,
                key,
                pageToken: MENU_PAGE_TOKEN,
                createdAt: Date.now()
            }));
            return writePendingEntries(pendingEntries) ? id : null;
        }

        function dispatchCommand(commandKey, commandId) {
            const key = normalizeCommandKey(commandKey);
            if (!key) return false;
            const id = String(commandId || "").trim() || createCommandId(key);
            const payload = Object.freeze({
                type: "__templateShortcutsMenuCommand",
                source: MENU_MESSAGE_SOURCE,
                siteId: SITE_ID,
                pageToken: MENU_PAGE_TOKEN,
                commandKey: key,
                commandId: id
            });
            try {
                if (scope && typeof scope.postMessage === 'function') {
                    scope.postMessage(payload, '*');
                    return true;
                }
            } catch {}
            if (!dispatchTarget || typeof CustomEvent !== 'function') return false;
            try {
                dispatchTarget.dispatchEvent(new CustomEvent("__templateShortcutsMenuCommand", {
                    detail: payload
                }));
                return true;
            } catch {
                return false;
            }
        }

        function invokeCommand(commandKey) {
            const key = normalizeCommandKey(commandKey);
            const commandConfig = commandConfigs.get(key) || null;
            const commandId = createCommandId(key);
            const queuedCommandId = queuePendingCommand(key, commandId);
            const effectiveCommandId = queuedCommandId || commandId;
            const dispatched = dispatchCommand(key, effectiveCommandId);
            if (isStatefulCommand(commandConfig)) {
                refreshCommandLabel(key);
            }
            if (queuedCommandId || dispatched) return;

            if (key === "settings" && typeof settingsHandler === 'function') {
                try {
                    settingsHandler();
                    return;
                } catch (error) {
                    console.error(`[${SITE_LABEL}] settings menu handler failed.`, error);
                    return;
                }
            }

            if (key === "settings") {
                console.warn(`[${SITE_LABEL}] settings menu clicked before handler was ready.`);
            }
        }

        function registerCommand(commandKey, label) {
            const config = buildCommandConfig(commandKey, label);
            if (!config || typeof register !== 'function') return null;
            const key = config.key;
            const text = String(resolveCommandLabel(config) || "").trim();
            if (!text) return null;

            const existing = commands.get(key) || null;
            commandConfigs.set(key, config);
            bindCommandStateListener(config);
            if (existing && existing.label === text && existing.commandId !== null && existing.commandId !== undefined) {
                return existing.commandId;
            }

            if (existing && existing.commandId !== null && existing.commandId !== undefined && typeof unregister === 'function') {
                try { unregister(existing.commandId); } catch {}
            }

            let commandId = null;
            try {
                commandId = register(text, () => invokeCommand(key));
            } catch (error) {
                console.warn(`[${SITE_LABEL}] Failed to register bootstrap menu "${text}".`, error);
                commandId = null;
            }

            commands.set(key, { label: text, commandId });
            return commandId;
        }

        function unregisterCommand(commandKey) {
            const key = normalizeCommandKey(commandKey);
            if (!key) return false;
            const existing = commands.get(key) || null;
            if (!existing) return false;
            if (existing.commandId !== null && existing.commandId !== undefined && typeof unregister === 'function') {
                try { unregister(existing.commandId); } catch {}
            }
            commands.delete(key);
            commandConfigs.delete(key);
            unbindCommandStateListener(key);
            return true;
        }

        function consumePending(commandKey) {
            const key = normalizeCommandKey(commandKey);
            if (!key) return 0;
            const pendingEntries = readPendingEntries();
            if (pendingEntries.length === 0) return 0;
            let count = 0;
            const remainingEntries = [];
            for (const entry of pendingEntries) {
                if (entry.key === key && entry.pageToken === MENU_PAGE_TOKEN) {
                    count += 1;
                    continue;
                }
                remainingEntries.push(entry);
            }
            writePendingEntries(remainingEntries);
            return count;
        }

        registerCommand("settings", `${SITE_LABEL} - 设置快捷键`);
        for (const command of BOOTSTRAP_MENU_COMMANDS) {
            if (command?.key === "settings") continue;
            registerCommand(command);
        }

        const bridge = {
            managedByBootstrap: typeof register === 'function',
            eventName: "__templateShortcutsMenuCommand",
            registerCommand,
            unregisterCommand,
            consumePending,
            dispatchCommand,
            setSettingsHandler(handler) {
                settingsHandler = typeof handler === 'function' ? handler : null;
                return settingsHandler !== null;
            },
            getSettingsCommandId() {
                return commands.get("settings")?.commandId ?? null;
            },
            getSettingsLabel() {
                return commands.get("settings")?.label || `${SITE_LABEL} - 设置快捷键`;
            }
        };

        if (scope) {
            try {
                Object.defineProperty(scope, "__TEMPLATE_SHORTCUTS_MENU_BRIDGE__", {
                    value: bridge,
                    configurable: true,
                    enumerable: false,
                    writable: true
                });
            } catch {
                try {
                    scope["__TEMPLATE_SHORTCUTS_MENU_BRIDGE__"] = bridge;
                } catch {}
            }
        }

        return Object.freeze(bridge);
    }

    async function getResourceUrl(name) {
        const fn = getUserscriptApi('GM_getResourceURL');
        if (typeof fn !== 'function') {
            throw new Error(`GM_getResourceURL is unavailable for resource "${name}"`);
        }

        const value = await Promise.resolve(fn(name));
        const url = typeof value === 'string' ? value.trim() : '';
        if (!url) {
            throw new Error(`GM_getResourceURL returned an empty URL for resource "${name}"`);
        }
        return url;
    }

    async function prepareModuleUrl(name) {
        const rawUrl = await getResourceUrl(name);

        try {
            const response = await fetch(rawUrl);
            if (!response.ok) {
                throw new Error(`HTTP ${response.status}`);
            }

            const source = await response.text();
            const blob = new Blob([source], { type: 'text/javascript;charset=utf-8' });
            return {
                rawUrl,
                moduleUrl: URL.createObjectURL(blob)
            };
        } catch (error) {
            console.warn(`[${SITE_LABEL}] Failed to rewrap resource "${name}" as a module blob URL. Falling back to the original resource URL.`, error);
            return {
                rawUrl,
                moduleUrl: rawUrl
            };
        }
    }

    exposeUserscriptApiResolver();
    const menuBridge = createMenuBridge();

    async function main() {
        const preparedCore = await prepareModuleUrl(RESOURCE_NAMES.core);
        const preparedSite = await prepareModuleUrl(RESOURCE_NAMES.site);
        const resourceUrls = Object.freeze({
            core: preparedCore.rawUrl,
            site: preparedSite.rawUrl
        });
        const moduleUrls = Object.freeze({
            core: preparedCore.moduleUrl,
            site: preparedSite.moduleUrl
        });

        const siteModule = await import(moduleUrls.site);
        const startSite = typeof siteModule?.startSite === 'function'
            ? siteModule.startSite
            : (typeof siteModule?.default === 'function' ? siteModule.default : null);

        if (typeof startSite !== 'function') {
            throw new Error('Site module must export startSite(runtime).');
        }

        await startSite(Object.freeze({
            siteId: SITE_ID,
            displayName: SITE_LABEL,
            resourceNames: RESOURCE_NAMES,
            resourceUrls,
            moduleUrls,
            bootstrapMenuManaged: BOOTSTRAP_MENU_COMMANDS.length > 0,
            menuMessageType: "__templateShortcutsMenuCommand",
            menuMessageSource: "template-shortcuts-userscript",
            menuPendingValueKey: MENU_PENDING_VALUE_KEY,
            menuPageToken: MENU_PAGE_TOKEN,
            menuBridge,
            getUserscriptApi,
            getResourceUrl
        }));
    }

    void main().catch((error) => {
        console.error(`[${SITE_LABEL}] userscript bootstrap failed.`, error);
    });
})();
