// ==UserScript==
// @name           [LINUX DO] 快捷键跳转 [20260508] v1.0.0
// @name:en        [LINUX DO] Shortcut Jump [20260508] v1.0.0
// @namespace      https://github.com/0-V-linuxdo/Template_shortcuts.js
// @description    为 Linux Do 提供可视化快捷键中心：支持 URL 跳转、元素点击、按键模拟、搜索模板变量与图标库管理，并适配 Discourse 的 SPA 导航场景。
// @description:en A visual shortcut center for Linux Do with URL jumps, element clicks, key simulation, search template variables, icon library management, and Discourse SPA navigation support.

// @version        [20260508] v1.0.0
// @update-log     1.0.0: 保留原键帽样式，将 Linux Do 脚本图标键帽改为普通模式黑色、黑暗模式白色自适应。
// @update-log:en  1.0.0: Kept the original keycap style and made the Linux Do script icon keycap adapt to black in light mode and white in dark mode.

// @match          https://linux.do/*

// @grant          GM_registerMenuCommand
// @grant          GM_getValue
// @grant          GM_setValue
// @grant          GM_xmlhttpRequest
// @grant          GM_unregisterMenuCommand

// @connect        *

// @icon           data:image/svg+xml,%3Csvg%20viewBox%3D%220%200%2064%2064%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20aria-hidden%3D%22true%22%20role%3D%22img%22%20preserveAspectRatio%3D%22xMidYMid%20meet%22%20class%3D%22linux-do-keycap-icon%22%3E%20%3Cstyle%3E%20%3Aroot%20%7B%20color-scheme%3A%20light%20dark%3B%20%7D%20.linux-do-keycap-icon%20%7B%20color%3A%20%23000000%3B%20%7D%20%40media%20(prefers-color-scheme%3A%20dark)%20%7B%20.linux-do-keycap-icon%20%7B%20color%3A%20%23FFFFFF%3B%20%7D%20%7D%20%3C%2Fstyle%3E%20%3Cpath%20d%3D%22M52%202H12C6.478%202%202%206.477%202%2011.999V52c0%205.522%204.478%2010%2010%2010h40c5.522%200%2010-4.478%2010-10V11.999C62%206.477%2057.522%202%2052%202zm5%2043.666A8.333%208.333%200%200%201%2048.667%2054H15.333A8.333%208.333%200%200%201%207%2045.666V12.333A8.332%208.332%200%200%201%2015.333%204h33.334A8.332%208.332%200%200%201%2057%2012.333v33.333z%22%20fill%3D%22currentColor%22%20fill-rule%3D%22evenodd%22%20clip-rule%3D%22evenodd%22%3E%3C%2Fpath%3E%20%3Cdefs%3E%3CclipPath%20id%3D%22linux-do-keycap-clip%22%3E%3Ccircle%20cx%3D%2260%22%20cy%3D%2260%22%20r%3D%2247%22%3E%3C%2Fcircle%3E%3C%2FclipPath%3E%3C%2Fdefs%3E%3Cg%20transform%3D%22translate(12%207)%20scale(0.3333)%22%3E%3Ccircle%20fill%3D%22%23f0f0f0%22%20cx%3D%2260%22%20cy%3D%2260%22%20r%3D%2250%22%3E%3C%2Fcircle%3E%3Crect%20fill%3D%22%231c1c1e%22%20clip-path%3D%22url(%23linux-do-keycap-clip)%22%20x%3D%2210%22%20y%3D%2210%22%20width%3D%22100%22%20height%3D%2230%22%3E%3C%2Frect%3E%3Crect%20fill%3D%22%23f0f0f0%22%20clip-path%3D%22url(%23linux-do-keycap-clip)%22%20x%3D%2210%22%20y%3D%2240%22%20width%3D%22100%22%20height%3D%2240%22%3E%3C%2Frect%3E%3Crect%20fill%3D%22%23ffb003%22%20clip-path%3D%22url(%23linux-do-keycap-clip)%22%20x%3D%2210%22%20y%3D%2280%22%20width%3D%22100%22%20height%3D%2230%22%3E%3C%2Frect%3E%3C%2Fg%3E%20%3C%2Fsvg%3E
// @require        https://github.com/0-V-linuxdo/Template_shortcuts.js/raw/refs/heads/release/Template_JS/%5BTemplate%5D%20shortcut%20core.js?v=20260605.1.0.0
// ==/UserScript==

/* ===================== IMPORTANT · NOTICE · START =====================
 *
 * 1. [编辑指引 | Edit Guidance]
 *    • ⚠️ 这是一个自动生成的文件：请不要直接修改当前产物。
 *    • ⚠️ 源码真源位于当前仓库 `main` 分支的 `src/modules/` 与 `src/sites/`；站点元数据位于 `src/sites/manifest.js`；Template 头部元数据位于 `src/userscript/header.txt`。
 *    • ⚠️ 在 `main` 分支运行 `npm run build` 会刷新本地 `Template_JS/` 与 `Site_JS/`。
 *    • ⚠️ 最新发布物应同步到当前仓库的 `release` 分支；release userscript 通过 `@require` 加载 `Template_JS/[Template] shortcut core.js`；`archive/` 仅保存历史归档与参考资料，不参与当前运行时加载。
 *    • ⚠️ This is a generated artifact. Do not edit this file directly. The source of truth lives in the current repository's `main` branch under `src/modules/`, `src/sites/`, `src/sites/manifest.js`, and `src/userscript/header.txt`. Run `npm run build` on `main` to refresh local `Template_JS/` and `Site_JS/` outputs, then stage release assets for the repository's `release` branch.
 *
 * ----------------------------------------------------------------------
 *
 * 2. [安全提示 | Safety Reminder]
 *    • ✅ 必须使用 `setTrustedHTML`，不得使用 `innerHTML`。
 *    • ✅ Always call `setTrustedHTML`; never rely on `innerHTML`.
 *
 * ====================== IMPORTANT · NOTICE · END ======================
 */

(() => {
  // src/sites/linux-do/index.js
  (function() {
    "use strict";
    const ShortcutTemplate = window.ShortcutTemplate;
    if (!ShortcutTemplate || typeof ShortcutTemplate.createShortcutEngine !== "function") {
      console.error("[Linux Do Shortcut] Template module not found.");
      return;
    }
    const logTag = "[Linux Do Shortcut Script]";
    const TemplateUtils = ShortcutTemplate?.utils || {};
    const SHORTCUTS_STORAGE_KEY = "linuxdo_shortcuts_v3";
    const ICON_CACHE_PREFIX = "linuxdo_icon_cache_v2::";
    const USER_ICONS_STORAGE_KEY = "linuxdo_user_icons_v2";
    const ICON_THEME_ADAPTED_STORAGE_KEY = "linuxdo_icon_theme_adapted_v1";
    const defaultIconURL = "https://linux.do/logo-1024.svg";
    const MANAGED_SHORTCUT_KEYS = Object.freeze({
      newestCreated: "linuxdo.newestCreated",
      myTopics: "linuxdo.myTopics",
      bookmarks: "linuxdo.bookmarks",
      topByViews: "linuxdo.topByViews",
      latestTopicSearch: "linuxdo.latestTopicSearch",
      latest: "linuxdo.latest",
      top: "linuxdo.top",
      categories: "linuxdo.categories",
      tags: "linuxdo.tags"
    });
    const MANAGED_SHORTCUT_KEY_SET = new Set(Object.values(MANAGED_SHORTCUT_KEYS));
    const defaultIcons = [
      { name: "Linux Do", url: defaultIconURL },
      { name: "ChatGPT", url: "https://chatgpt.com/favicon.ico" },
      { name: "Claude", url: "https://claude.ai/favicon.ico" },
      { name: "Gemini", url: "https://www.gstatic.com/lamda/images/gemini_sparkle_v002_d4735304ff6292a690345.svg" },
      { name: "Perplexity", url: "https://www.perplexity.ai/favicon.svg" },
      { name: "Copilot", url: "https://copilot.microsoft.com/favicon.ico" },
      { name: "Poe", url: "https://psc2.cf2.poecdn.net/assets/favicon.svg" },
      { name: "Kimi", url: "https://statics.moonshot.cn/kimi-chat/favicon.ico" },
      { name: "Doubao", url: "https://lf-flow-web-cdn.doubao.com/obj/flow-doubao/doubao/web/logo-icon.png" },
      { name: "GitHub", url: "https://github.githubassets.com/favicons/favicon.svg" },
      { name: "Stack Overflow", url: "https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico" },
      { name: "Reddit", url: "https://www.reddit.com/favicon.ico" },
      { name: "Google", url: "https://www.google.com/favicon.ico" },
      { name: "Wikipedia", url: "https://www.wikipedia.org/static/favicon/wikipedia.ico" }
    ];
    const protectedIconUrls = [defaultIconURL];
    const SITE_MESSAGES = Object.freeze({
      "zh-CN": {
        menuCommandLabel: "Linux Do - 设置快捷键",
        panelTitle: "Linux Do - 自定义快捷键",
        shortcuts: {
          "New created": "最新创建",
          "My Topic": "我的主题",
          "Views": "浏览量",
          "Search: latest_topic": "搜索：latest_topic"
        }
      },
      "en-US": {
        menuCommandLabel: "Linux Do - Shortcut settings",
        panelTitle: "Linux Do - Custom shortcuts",
        shortcuts: {
          "书签": "Bookmarks",
          "最新帖子": "Latest posts",
          "热门帖子": "Hot posts",
          "分类页": "Categories",
          "标签页": "Tags"
        }
      }
    });
    const baseShortcut = {
      url: "",
      urlMethod: "current",
      urlAdvanced: "href",
      selector: "",
      simulateKeys: "",
      icon: defaultIconURL,
      customAction: "",
      data: {}
    };
    const createShortcut = (overrides) => ({ ...baseShortcut, ...overrides });
    const defaultShortcuts = [
      createShortcut({
        key: MANAGED_SHORTCUT_KEYS.newestCreated,
        name: "New created",
        actionType: "url",
        url: "https://linux.do/latest?order=created",
        urlMethod: "spa",
        urlAdvanced: "pushState",
        hotkey: "CTRL+N"
      }),
      createShortcut({
        key: MANAGED_SHORTCUT_KEYS.myTopics,
        name: "My Topic",
        actionType: "url",
        url: "https://linux.do/u/0_v/activity/topics",
        urlMethod: "spa",
        urlAdvanced: "pushState",
        hotkey: "CTRL+M"
      }),
      createShortcut({
        key: MANAGED_SHORTCUT_KEYS.bookmarks,
        name: "书签",
        actionType: "url",
        url: "https://linux.do/u/0_v/activity/bookmarks",
        urlMethod: "spa",
        urlAdvanced: "pushState",
        hotkey: "CTRL+B"
      }),
      createShortcut({
        key: MANAGED_SHORTCUT_KEYS.topByViews,
        name: "Views",
        actionType: "url",
        url: "https://linux.do/top?ascending=false&order=views",
        urlMethod: "spa",
        urlAdvanced: "pushState",
        hotkey: "CTRL+V"
      }),
      createShortcut({
        key: MANAGED_SHORTCUT_KEYS.latestTopicSearch,
        name: "Search: latest_topic",
        actionType: "url",
        url: "https://linux.do/search?q=%s+order:latest_topic",
        urlMethod: "spa",
        urlAdvanced: "pushState",
        hotkey: "CTRL+U"
      }),
      createShortcut({
        key: MANAGED_SHORTCUT_KEYS.latest,
        name: "最新帖子",
        actionType: "url",
        url: "https://linux.do/latest",
        urlMethod: "spa",
        urlAdvanced: "href",
        hotkey: "CTRL+L"
      }),
      createShortcut({
        key: MANAGED_SHORTCUT_KEYS.top,
        name: "热门帖子",
        actionType: "url",
        url: "https://linux.do/top",
        urlMethod: "spa",
        urlAdvanced: "pushState",
        hotkey: "CTRL+T"
      }),
      createShortcut({
        key: MANAGED_SHORTCUT_KEYS.categories,
        name: "分类页",
        actionType: "url",
        url: "https://linux.do/categories",
        urlMethod: "spa",
        urlAdvanced: "pushState",
        hotkey: "CTRL+SHIFT+C"
      }),
      createShortcut({
        key: MANAGED_SHORTCUT_KEYS.tags,
        name: "标签页",
        actionType: "url",
        url: "https://linux.do/tags",
        urlMethod: "spa",
        urlAdvanced: "pushState",
        hotkey: "CTRL+SHIFT+T"
      })
    ];
    const MANAGED_ACTION_ICON_MAP = Object.freeze(defaultShortcuts.reduce((map, shortcut) => {
      if (!shortcut || typeof shortcut !== "object") return map;
      const key = String(shortcut.key || "").trim();
      const icon = String(shortcut.icon || "").trim();
      if (!MANAGED_SHORTCUT_KEY_SET.has(key) || !icon) return map;
      map[key] = icon;
      return map;
    }, {}));
    const MANAGED_ACTION_ICON_SET = new Set(Object.values(MANAGED_ACTION_ICON_MAP));
    function syncManagedActionIcons(engineInstance) {
      if (!engineInstance || typeof engineInstance.getShortcuts !== "function" || typeof engineInstance.setShortcuts !== "function") {
        return;
      }
      const shortcuts = engineInstance.getShortcuts();
      if (!Array.isArray(shortcuts) || shortcuts.length === 0) return;
      let changed = false;
      const patched = shortcuts.map((item) => {
        if (!item || typeof item !== "object") return item;
        const key = String(item.key || "").trim();
        if (!key) return item;
        const targetIcon = MANAGED_ACTION_ICON_MAP[key];
        if (!targetIcon) return item;
        const currentIcon = typeof item.icon === "string" ? item.icon : "";
        const shouldPatch = !currentIcon || /currentColor/i.test(currentIcon) || MANAGED_ACTION_ICON_SET.has(currentIcon);
        if (!shouldPatch || currentIcon === targetIcon) return item;
        changed = true;
        return { ...item, icon: targetIcon };
      });
      if (changed) {
        engineInstance.setShortcuts(patched);
      }
    }
    function parseContainsSelector(selector) {
      const match = String(selector || "").match(/^(.*):contains\((['"])(.+)\2\)\s*$/);
      if (!match) return null;
      return {
        baseSelector: String(match[1] || "").trim(),
        text: String(match[3] || "").trim()
      };
    }
    function resolveSelectorWithContains(selector) {
      const parsed = parseContainsSelector(selector);
      if (!parsed || !parsed.baseSelector) return null;
      let elements = [];
      try {
        elements = Array.from(document.querySelectorAll(parsed.baseSelector));
      } catch {
        return null;
      }
      const matched = elements.find((el) => String(el.textContent || "").trim().includes(parsed.text));
      if (!matched) return null;
      return matched.closest('button, a, [role="button"], [onclick]') || matched;
    }
    function findElementBySelector(selector) {
      const sel = String(selector || "").trim();
      if (!sel) return null;
      if (sel.includes(":contains(")) {
        return resolveSelectorWithContains(sel);
      }
      try {
        return document.querySelector(sel);
      } catch {
        return null;
      }
    }
    function triggerClickChain(element) {
      if (!element) return false;
      try {
        const ok = TemplateUtils?.events?.simulateClick?.(element, { nativeFallback: true });
        if (ok) return true;
      } catch {
      }
      try {
        if (typeof element.click === "function") {
          element.click();
          return true;
        }
      } catch {
      }
      try {
        const evt = new MouseEvent("click", { bubbles: true, cancelable: true, view: window });
        element.dispatchEvent(evt);
        return true;
      } catch {
      }
      return false;
    }
    function linuxdoSelectorHandler({ shortcut }) {
      const selector = typeof shortcut?.selector === "string" ? shortcut.selector.trim() : "";
      if (!selector) {
        console.warn(`${logTag} selector action has empty selector:`, shortcut?.name || "(unnamed)");
        return false;
      }
      const target = findElementBySelector(selector);
      if (!target) {
        console.warn(`${logTag} selector target not found:`, selector);
        return false;
      }
      const clickable = target.closest?.('button, a, [role="button"], [onclick]') || target;
      const ok = triggerClickChain(clickable);
      if (!ok) {
        console.warn(`${logTag} selector click failed:`, selector, clickable);
      }
      return ok;
    }
    function getCurrentSearchTerm() {
      try {
        const fromUrl = new URL(location.href).searchParams.get("q");
        if (typeof fromUrl === "string" && fromUrl.trim()) {
          return fromUrl.trim();
        }
      } catch {
      }
      const searchInputSelectors = [
        "#search-term",
        "input.search-query",
        'input[type="search"]',
        ".search-input input"
      ];
      for (const selector of searchInputSelectors) {
        try {
          const input = document.querySelector(selector);
          const value = input && typeof input.value === "string" ? input.value.trim() : "";
          if (value) return value;
        } catch {
        }
      }
      try {
        if (location.pathname.includes("/search")) {
          const title = String(document.title || "").trim();
          const titleMatch = title.match(/["“](.+?)["”]/) || title.match(/Search\s+results\s+for\s+(.+?)\s*[-|]/i);
          if (titleMatch && titleMatch[1]) {
            return titleMatch[1].trim();
          }
        }
      } catch {
      }
      return "";
    }
    function resolveUrlTemplate(targetUrl, { getCurrentSearchTerm: getTerm, placeholderToken }) {
      const placeholder = placeholderToken || "%s";
      const url = String(targetUrl || "");
      if (!url.includes(placeholder)) return url;
      let keyword = "";
      try {
        keyword = typeof getTerm === "function" ? String(getTerm() || "").trim() : "";
      } catch (err) {
        console.warn(`${logTag} resolveUrlTemplate failed:`, err);
      }
      if (keyword) {
        return url.replaceAll(placeholder, encodeURIComponent(keyword));
      }
      if (placeholder === "%s" && url.includes("/search?q=")) {
        const qIndex = url.indexOf("?");
        return qIndex > -1 ? url.slice(0, qIndex) : url;
      }
      return url.replaceAll(placeholder, "");
    }
    const engine = ShortcutTemplate.createShortcutEngine({
      menuCommandLabel: "Linux Do - 设置快捷键",
      panelTitle: "Linux Do - 自定义快捷键",
      storageKeys: {
        shortcuts: SHORTCUTS_STORAGE_KEY,
        iconCachePrefix: ICON_CACHE_PREFIX,
        userIcons: USER_ICONS_STORAGE_KEY,
        iconThemeAdapted: ICON_THEME_ADAPTED_STORAGE_KEY
      },
      iconThemeAdapt: {
        enabled: true,
        lightFillColor: "#111827",
        darkFillColor: "#F8FAFC"
      },
      ui: {
        idPrefix: "linuxdo",
        cssPrefix: "linuxdo",
        compactBreakpoint: 800
      },
      i18n: {
        messages: SITE_MESSAGES
      },
      defaultIconURL,
      iconLibrary: defaultIcons,
      protectedIconUrls,
      defaultShortcuts,
      actionHandlers: {
        selector: linuxdoSelectorHandler
      },
      allowOverrideBuiltinActions: true,
      actionTypeMeta: {
        selector: {
          label: "Element click",
          shortLabel: "Click",
          color: "#FF9800",
          builtin: true
        }
      },
      consoleTag: logTag,
      colors: {
        primary: "#5D5CDE"
      },
      shouldBypassIconCache: (url) => {
        const value = String(url || "");
        return value.startsWith("https://linux.do/") || value.startsWith("https://cdn-lfs.linux.do/") || value.startsWith("data:image/");
      },
      getCurrentSearchTerm,
      resolveUrlTemplate,
      placeholderToken: "%s",
      text: {
        stats: {
          total: "总计",
          url: "URL跳转",
          selector: "元素点击",
          simulate: "按键模拟",
          custom: "自定义动作"
        },
        buttons: {
          addShortcut: "添加新快捷键",
          saveAndClose: "保存并关闭",
          confirm: "确定",
          cancel: "取消",
          delete: "删除",
          edit: "编辑",
          clear: "清除"
        },
        dialogs: {
          alert: "提示",
          confirm: "确认",
          prompt: "输入"
        },
        hints: {
          hotkey: "点击此处，然后按下快捷键组合",
          simulate: "点击此处，然后按下要模拟的按键组合",
          hotkeyHelp: "💡 支持 Ctrl/Shift/Alt/Cmd + 字母/数字/功能键等组合",
          simulateHelp: "⚡ 将模拟这个按键组合发送到网页"
        },
        menuLabelFallback: "打开快捷键设置"
      }
    });
    engine.init();
    syncManagedActionIcons(engine);
    if (typeof window !== "undefined") {
      window.LinuxDoShortcutEngine = engine;
    }
    console.log(`${logTag} 快捷键引擎已启动，基于 Template 模块 v${ShortcutTemplate.VERSION}`);
  })();
})();
