// ==UserScript==
// @name           [Poe] 快捷键跳转 [20260423] v1.0.5
// @name:en        [Poe] Shortcut Jump [20260423] v1.0.5
// @namespace      https://github.com/0-V-linuxdo/Template_shortcuts.js
// @description    为 Poe 提供可视化快捷键中心：支持 URL 跳转、元素点击、按键模拟、自定义动作，并内置消息复制/编辑、重命名保存与侧边栏切换等站点专属操作。
// @description:en A visual shortcut center for Poe with URL jumps, element clicks, key simulation, custom actions, message copy/edit, rename save, and sidebar toggles.

// @version        [20260423] v1.0.5
// @update-log     1.0.5: 恢复 legacy require 架构，移除桥接式启动链。
// @update-log:en  1.0.5: Restored the legacy require architecture and removed the bridged startup chain.

// @match          https://poe.com/*

// @grant          GM_registerMenuCommand
// @grant          GM_unregisterMenuCommand
// @grant          GM_getValue
// @grant          GM_setValue
// @grant          GM_xmlhttpRequest

// @connect        *

// @icon           https://psc2.cf2.poecdn.net/assets/favicon.svg
// @require        https://github.com/0-V-linuxdo/Template_shortcuts.js/raw/refs/heads/release/Template_JS/%5BTemplate%5D%20shortcut%20core.js?v=20260429.1.3.1
// ==/UserScript==

/* ===================== IMPORTANT · NOTICE · START =====================
 *
 * 1. [编辑指引 | Edit Guidance]
 *    • ⚠️ 这是一个自动生成的文件：请不要直接修改当前产物。
 *    • ⚠️ 源码真源位于当前仓库 `main` 分支的 `src/modules/` 与 `src/sites/`；站点元数据位于 `src/sites/manifest.js`；Template 头部元数据位于 `src/userscript/header.txt`。
 *    • ⚠️ 在 `main` 分支运行 `npm run build` 会刷新本地 `Template_JS/` 与 `Site_JS/`。
 *    • ⚠️ 最新发布物应同步到当前仓库的 `release` 分支；release userscript 通过 `@require` 加载 `Template_JS/[Template] shortcut core.js`；`archive/` 仅保存历史归档与参考资料，不参与当前运行时加载。
 *    • ⚠️ This is a generated artifact. Do not edit this file directly. The source of truth lives in the current repository's `main` branch under `src/modules/`, `src/sites/`, `src/sites/manifest.js`, and `src/userscript/header.txt`. Run `npm run build` on `main` to refresh local `Template_JS/` and `Site_JS/` outputs, then stage release assets for the repository's `release` branch.
 *
 * ----------------------------------------------------------------------
 *
 * 2. [安全提示 | Safety Reminder]
 *    • ✅ 必须使用 `setTrustedHTML`，不得使用 `innerHTML`。
 *    • ✅ Always call `setTrustedHTML`; never rely on `innerHTML`.
 *
 * ====================== IMPORTANT · NOTICE · END ======================
 */

(() => {
  // src/sites/poe/index.js
  (function() {
    "use strict";
    function gmGetValueLocal(key, fallback) {
      if (typeof GM_getValue !== "function") return fallback;
      try {
        const value = GM_getValue(key, fallback);
        return value === void 0 ? fallback : value;
      } catch {
        return fallback;
      }
    }
    function gmSetValueLocal(key, value) {
      if (typeof GM_setValue !== "function") return;
      try {
        GM_setValue(key, value);
      } catch {
      }
    }
    function gmRegisterMenuCommandLocal(label, handler) {
      if (typeof GM_registerMenuCommand !== "function") return null;
      try {
        return GM_registerMenuCommand(label, handler);
      } catch {
        return null;
      }
    }
    function gmUnregisterMenuCommandLocal(commandId) {
      if (typeof GM_unregisterMenuCommand !== "function") return;
      try {
        GM_unregisterMenuCommand(commandId);
      } catch {
      }
    }
    const ShortcutTemplate = window.ShortcutTemplate;
    if (!ShortcutTemplate || typeof ShortcutTemplate.createShortcutEngine !== "function") {
      console.error("[Poe Shortcut] Template module not found.");
      return;
    }
    const logTag = "[Poe Shortcut Script]";
    const TemplateUtils = ShortcutTemplate?.utils || {};
    const SHORTCUTS_STORAGE_KEY = "poe_shortcuts_v3";
    const ICON_CACHE_PREFIX = "poe_icon_cache_v3::";
    const USER_ICONS_STORAGE_KEY = "poe_user_icons_v3";
    const ICON_THEME_ADAPTED_STORAGE_KEY = "poe_icon_theme_adapted_v2";
    const SIDEBAR_VISIBILITY_STORAGE_KEY = "poe_keep_sidebar_visible_v1";
    const DEFAULT_KEEP_SIDEBAR_VISIBLE = true;
    let keepSidebarVisible = getKeepSidebarVisibleSetting();
    let sidebarVisibilityMenuCommandId = null;
    let engineInstance = null;
    const defaultIconURL = "https://psc2.cf2.poecdn.net/assets/favicon.svg";
    const SITE_MESSAGES = Object.freeze({
      "zh-CN": {
        menuCommandLabel: "Poe - 设置快捷键",
        panelTitle: "Poe - 自定义快捷键",
        keepSidebarVisibleLabel: "Poe - 保持侧边栏显示: {state}",
        on: "开",
        off: "关",
        shortcuts: {
          "App-Creator": "App Creator",
          "Explore": "探索",
          "History": "历史",
          "Settings": "设置",
          "New Chat": "新建聊天",
          "侧边栏切换": "切换侧边栏",
          "重试": "重试",
          "保存重命名": "保存重命名",
          "复制消息": "复制消息",
          "编辑消息": "编辑消息"
        },
        dataAdapters: {
          poeMessageAction: {
            label: "消息动作（copy / edit 或 JSON）:",
            placeholder: '例如: copy 或 edit；也可输入 {"action":"copy"}'
          }
        }
      },
      "en-US": {
        menuCommandLabel: "Poe - Shortcut settings",
        panelTitle: "Poe - Custom shortcuts",
        keepSidebarVisibleLabel: "Poe - Keep sidebar visible: {state}",
        on: "On",
        off: "Off",
        shortcuts: {
          "侧边栏切换": "Toggle sidebar",
          "重试": "Retry",
          "保存重命名": "Save rename",
          "复制消息": "Copy message",
          "编辑消息": "Edit message"
        },
        dataAdapters: {
          poeMessageAction: {
            label: "Message action (copy / edit or JSON):",
            placeholder: 'Example: copy or edit; JSON also works: {"action":"copy"}'
          }
        }
      }
    });
    const siteText = (key, fallback) => ({ ctx } = {}) => ctx?.i18n?.t?.(key, {}, fallback) || fallback;
    const APP_CREATOR_ICON = "https://qph.cf2.poecdn.net/main-thumb-pb-5003-50-zdgktfpcizyaajmazqorxwnwlzhiwdmi.jpeg";
    const RENAME_SAVE_BUTTON_SELECTOR = "button.button_primary__Vo3KL";
    function getKeepSidebarVisibleSetting() {
      try {
        const value = gmGetValueLocal(SIDEBAR_VISIBILITY_STORAGE_KEY, DEFAULT_KEEP_SIDEBAR_VISIBLE);
        if (value && typeof value.then === "function") return DEFAULT_KEEP_SIDEBAR_VISIBLE;
        return value === true || value === "true";
      } catch {
      }
      return DEFAULT_KEEP_SIDEBAR_VISIBLE;
    }
    function setKeepSidebarVisibleSetting(value) {
      try {
        gmSetValueLocal(SIDEBAR_VISIBILITY_STORAGE_KEY, !!value);
      } catch {
      }
    }
    function getSidebarVisibilityMenuLabel() {
      const stateText = engineInstance?.i18n?.t?.(keepSidebarVisible ? "on" : "off", {}, keepSidebarVisible ? "On" : "Off") || (keepSidebarVisible ? "On" : "Off");
      return engineInstance?.i18n?.t?.("keepSidebarVisibleLabel", { state: stateText }, `Poe - Keep sidebar visible: ${stateText}`) || `Poe - Keep sidebar visible: ${stateText}`;
    }
    function registerSidebarVisibilityMenuCommand() {
      if (sidebarVisibilityMenuCommandId !== null) {
        try {
          gmUnregisterMenuCommandLocal(sidebarVisibilityMenuCommandId);
        } catch {
        }
      }
      sidebarVisibilityMenuCommandId = gmRegisterMenuCommandLocal(getSidebarVisibilityMenuLabel(), () => {
        setSidebarVisibilityPreference(!keepSidebarVisible);
      });
    }
    const MANAGED_SHORTCUT_KEYS = Object.freeze({
      explore: "poe.explore",
      history: "poe.history",
      settings: "poe.settings",
      newChat: "poe.newChat",
      sidebarToggle: "poe.sidebarToggle",
      retry: "poe.retry",
      saveRename: "poe.saveRename",
      copyMessage: "poe.copyMessage",
      editMessage: "poe.editMessage"
    });
    const MANAGED_SHORTCUT_KEY_SET = new Set(Object.values(MANAGED_SHORTCUT_KEYS));
    const defaultIcons = [
      { name: "Poe", url: defaultIconURL },
      { name: "App-Creator", url: APP_CREATOR_ICON },
      { name: "ChatGPT", url: "https://chatgpt.com/favicon.ico" },
      { name: "OpenAI", url: "https://openai.com/favicon.ico" },
      { name: "Claude", url: "https://claude.ai/favicon.ico" },
      { name: "Google", url: "https://www.google.com/favicon.ico" },
      { name: "Bing", url: "https://www.bing.com/favicon.ico" },
      { name: "DuckDuckGo", url: "https://duckduckgo.com/favicon.ico" },
      { name: "Wikipedia", url: "https://www.wikipedia.org/static/favicon/wikipedia.ico" },
      { name: "Reddit", url: "https://www.reddit.com/favicon.ico" },
      { name: "Stack Overflow", url: "https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico" },
      { name: "GitHub", url: "https://github.githubassets.com/favicons/favicon.svg" },
      { name: "Twitter / X", url: "https://abs.twimg.com/favicons/twitter.3.ico" },
      { name: "YouTube", url: "https://www.youtube.com/favicon.ico" }
    ];
    const protectedIconUrls = [
      defaultIconURL,
      APP_CREATOR_ICON
    ];
    const SELECTORS = {
      newChat: "div.BaseNavbar_rightNavItem__3DfWJ a span.button_label__mCaDf:contains('New chat')",
      sidebarToggleIcon: ".ToggleSidebarCollapseButton_hamburgerIcon__VuiyV",
      retryButton: "button[aria-label='Retry']",
      openDialog: '.ReactModal__Content--after-open[role="dialog"][aria-modal="true"]',
      renameModal: ".ChatRenameModal_modalContainer__hnsEx",
      renameSaveButton: `.ChatRenameModal_modalContainer__hnsEx ${RENAME_SAVE_BUTTON_SELECTOR}`,
      message: ".ChatMessage_chatMessage__xkgHx",
      overflowButtons: [
        ".ChatMessage_messageOverflowButton__8PaKN",
        'button[aria-label="More actions"]',
        "button[aria-expanded]",
        ".DropdownMenuButton_wrapper__uc04T button",
        ".ChatMessageOverflowButton_overflowButtonWrapper__gzb2s button"
      ],
      menuContainers: ['[role="menu"]', ".DropdownMenu_menu", "[data-menu]", ".menu"],
      menuItems: ['button[role="menuitem"]', '[role="menuitem"]', ".menu-item", "button"]
    };
    const SIDEBAR_EXPANDED_SELECTORS = [
      ".ChatSidebar_sidebarContainer__expanded",
      '[aria-expanded="true"]',
      ".sidebar-expanded"
    ];
    const MESSAGE_ACTION_PATTERNS = {
      copy: {
        exact: /^(copy\s+message|复制\s*消息|复制\s*对话|拷贝\s*消息)$/i,
        loose: /copy|复制|拷贝/i
      },
      edit: {
        exact: /^(edit|编辑|修改)$/i,
        loose: /edit|编辑|修改/i
      }
    };
    function sleep(ms) {
      return new Promise((resolve) => setTimeout(resolve, ms));
    }
    function debounce(fn, delay = 260) {
      let timer = null;
      return function(...args) {
        clearTimeout(timer);
        timer = setTimeout(() => fn.apply(this, args), delay);
      };
    }
    function isElementVisible(el) {
      if (!el) return false;
      if (el.offsetParent !== null) return true;
      const rect = el.getBoundingClientRect ? el.getBoundingClientRect() : null;
      return !!rect && rect.width > 0 && rect.height > 0;
    }
    function normalizeMessageAction(value) {
      const action = String(value ?? "").trim().toLowerCase();
      return action === "copy" || action === "edit" ? action : "";
    }
    function tryTriggerClick(element) {
      if (!element) return false;
      try {
        const ok = TemplateUtils?.events?.simulateClick?.(element, { nativeFallback: true });
        if (ok) return true;
      } catch {
      }
      try {
        if (typeof element.click === "function") {
          element.click();
          return true;
        }
      } catch {
      }
      try {
        const evt = new MouseEvent("click", { bubbles: true, cancelable: true, view: window });
        element.dispatchEvent(evt);
        return true;
      } catch {
      }
      return false;
    }
    function parseContainsSelector(selector) {
      const match = String(selector || "").match(/^(.*):contains\((['"])(.+)\2\)\s*$/);
      if (!match) return null;
      return {
        baseSelector: String(match[1] || "").trim(),
        text: String(match[3] || "").trim()
      };
    }
    function resolveSelectorWithContains(selector) {
      const parsed = parseContainsSelector(selector);
      if (!parsed || !parsed.baseSelector) return null;
      const elements = Array.from(document.querySelectorAll(parsed.baseSelector));
      const target = elements.find((el) => String(el.textContent || "").trim().includes(parsed.text));
      if (!target) return null;
      return target.closest('button, a, [role="button"], [onclick]') || target;
    }
    function findElementBySelector(selector) {
      const sel = String(selector || "").trim();
      if (!sel) return null;
      if (sel === SELECTORS.retryButton) {
        const list = Array.from(document.querySelectorAll(sel));
        return list.length ? list[list.length - 1] : null;
      }
      if (sel.includes(":contains(")) {
        return resolveSelectorWithContains(sel);
      }
      if (sel === SELECTORS.sidebarToggleIcon || sel.includes("_hamburgerIcon__")) {
        const iconEl = document.querySelector(sel);
        if (!iconEl) return null;
        return iconEl.closest('button, [role="button"], a, div') || iconEl.parentElement || iconEl;
      }
      return document.querySelector(sel);
    }
    function clickElementEnhanced(selector) {
      const sel = String(selector || "").trim();
      if (!sel) {
        console.warn(`${logTag} selector is empty.`);
        return false;
      }
      let target = null;
      try {
        target = findElementBySelector(sel);
      } catch (err) {
        console.warn(`${logTag} selector parse failed:`, sel, err);
        return false;
      }
      if (!target) {
        console.warn(`${logTag} element not found:`, sel);
        return false;
      }
      const clickable = target.closest?.('button, a, [role="button"], [onclick]') || target;
      const ok = tryTriggerClick(clickable);
      if (!ok) {
        console.warn(`${logTag} click failed:`, sel, clickable);
      }
      return ok;
    }
    function findTargetMessage() {
      return document.querySelector(`${SELECTORS.message}:hover`) || Array.from(document.querySelectorAll(SELECTORS.message)).pop() || null;
    }
    function findOverflowButton(container) {
      if (!container) return null;
      for (const selector of SELECTORS.overflowButtons) {
        const button = container.querySelector(selector);
        if (button && isElementVisible(button)) return button;
      }
      return null;
    }
    function isMenuVisible() {
      for (const selector of SELECTORS.menuContainers) {
        const container = document.querySelector(selector);
        if (!container || !isElementVisible(container)) continue;
        const items = container.querySelectorAll(SELECTORS.menuItems.join(","));
        if (items.length > 0) return true;
      }
      return false;
    }
    function findMessageMenuItem(action) {
      const patterns = MESSAGE_ACTION_PATTERNS[action];
      if (!patterns) return null;
      const candidates = Array.from(document.querySelectorAll(SELECTORS.menuItems.join(","))).filter((item) => isElementVisible(item) && String(item.textContent || "").trim());
      for (const item of candidates) {
        const text = String(item.textContent || "").trim();
        if (patterns.exact.test(text)) return item;
      }
      for (const item of candidates) {
        const text = String(item.textContent || "").trim();
        if (patterns.loose.test(text)) return item;
      }
      return null;
    }
    function isSaveLabel(text) {
      const t = String(text || "").trim().toLowerCase();
      return t === "save" || t === "保存";
    }
    function findVisibleRenameModal() {
      const candidates = Array.from(document.querySelectorAll(SELECTORS.renameModal));
      const visible = candidates.filter((el) => isElementVisible(el));
      return visible.length ? visible[visible.length - 1] : null;
    }
    function findRenameSaveButton(renameModal) {
      const root = renameModal || document;
      for (const btn of root.querySelectorAll(RENAME_SAVE_BUTTON_SELECTOR)) {
        if (!isElementVisible(btn)) continue;
        const labelEl = btn.querySelector(".button_label__mCaDf");
        const label = String(labelEl?.textContent || btn.textContent || "");
        if (isSaveLabel(label)) return btn;
      }
      if (root !== document) {
        const openDialog = root?.closest?.(SELECTORS.openDialog);
        if (openDialog && openDialog !== root) {
          return findRenameSaveButton(openDialog);
        }
      }
      return null;
    }
    function getActiveRenameSaveButton(renameModal) {
      const modal = renameModal && isElementVisible(renameModal) ? renameModal : findVisibleRenameModal();
      if (!modal) return null;
      const strictMatch = findRenameSaveButton(modal);
      if (strictMatch) return strictMatch;
      const scopes = [
        modal.closest?.(SELECTORS.openDialog),
        document
      ];
      for (const scope of scopes) {
        if (!scope || typeof scope.querySelectorAll !== "function") continue;
        const candidates = Array.from(scope.querySelectorAll(SELECTORS.renameSaveButton)).filter((btn) => isElementVisible(btn));
        if (candidates.length > 0) {
          return candidates[candidates.length - 1];
        }
      }
      return null;
    }
    async function performPoeMessageAction(rawAction) {
      const action = normalizeMessageAction(rawAction);
      if (!action) {
        console.warn(`${logTag} invalid message action:`, rawAction);
        return false;
      }
      const targetMessage = findTargetMessage();
      if (!targetMessage) {
        console.warn(`${logTag} target message not found.`);
        return false;
      }
      const overflowButton = findOverflowButton(targetMessage);
      if (!overflowButton) {
        console.warn(`${logTag} overflow button not found.`);
        return false;
      }
      if (!tryTriggerClick(overflowButton)) {
        console.warn(`${logTag} failed to open message menu.`);
        return false;
      }
      const waitDeadline = Date.now() + 900;
      while (Date.now() < waitDeadline) {
        if (isMenuVisible()) break;
        await sleep(40);
      }
      let menuItem = null;
      for (let i = 0; i < 8; i++) {
        menuItem = findMessageMenuItem(action);
        if (menuItem) break;
        await sleep(30);
      }
      if (!menuItem) {
        console.warn(`${logTag} message menu item not found for action:`, action);
        try {
          document.body.click();
        } catch {
        }
        return false;
      }
      const ok = tryTriggerClick(menuItem);
      if (!ok) {
        console.warn(`${logTag} message menu item click failed for action:`, action);
      }
      return ok;
    }
    function saveRenameIfModalOpen() {
      const modal = findVisibleRenameModal();
      if (!modal) {
        console.warn(`${logTag} rename modal not found or not visible.`);
        return false;
      }
      const saveButton = getActiveRenameSaveButton(modal);
      if (!saveButton) {
        console.warn(`${logTag} rename modal opened but save button not found.`);
        return false;
      }
      const ok = tryTriggerClick(saveButton);
      if (!ok) console.warn(`${logTag} failed to trigger rename save button.`);
      return ok;
    }
    function isSidebarOpen() {
      const sidebarContainer = document.querySelector(".SidebarLayout_sidebarContainer__oGhkh");
      if (sidebarContainer && !sidebarContainer.classList.contains("SidebarLayout_collapsed__KoQY2")) {
        return true;
      }
      for (const selector of SIDEBAR_EXPANDED_SELECTORS) {
        const node = document.querySelector(selector);
        if (node && isElementVisible(node)) return true;
      }
      const sidebarIcon = document.querySelector(SELECTORS.sidebarToggleIcon);
      if (sidebarIcon) {
        const container = sidebarIcon.closest("div");
        if (container) {
          const width = Number.parseInt(window.getComputedStyle(container).width, 10);
          if (Number.isFinite(width) && width > 50) return true;
        }
      }
      return false;
    }
    function ensureSidebarVisible() {
      if (!keepSidebarVisible) return false;
      if (isSidebarOpen()) return true;
      return clickElementEnhanced(SELECTORS.sidebarToggleIcon);
    }
    const debouncedEnsureSidebarVisible = debounce(() => {
      if (!keepSidebarVisible) return;
      try {
        ensureSidebarVisible();
      } catch (err) {
        console.warn(`${logTag} ensureSidebarVisible failed:`, err);
      }
    }, 260);
    function setSidebarVisibilityPreference(nextValue) {
      keepSidebarVisible = !!nextValue;
      setKeepSidebarVisibleSetting(keepSidebarVisible);
      console.info(`${logTag} keep sidebar visible is now ${keepSidebarVisible ? "enabled" : "disabled"}.`);
      if (keepSidebarVisible) {
        debouncedEnsureSidebarVisible();
      }
      registerSidebarVisibilityMenuCommand();
      return keepSidebarVisible;
    }
    function setupKeepSidebarVisible() {
      window.addEventListener("load", () => {
        setTimeout(() => debouncedEnsureSidebarVisible(), 650);
      }, { once: true });
      if (document.readyState === "complete") {
        setTimeout(() => debouncedEnsureSidebarVisible(), 800);
      }
      let lastUrl = location.href;
      const observer = new MutationObserver(() => {
        const currentUrl = location.href;
        if (currentUrl !== lastUrl) {
          lastUrl = currentUrl;
          debouncedEnsureSidebarVisible();
        }
      });
      observer.observe(document.documentElement || document, { subtree: true, childList: true });
      document.addEventListener("visibilitychange", () => {
        if (document.visibilityState === "visible") {
          debouncedEnsureSidebarVisible();
        }
      });
    }
    const CUSTOM_ACTION_DATA_ADAPTERS = {
      poeMessageAction: {
        label: siteText("dataAdapters.poeMessageAction.label", "Message action (copy / edit or JSON):"),
        placeholder: siteText("dataAdapters.poeMessageAction.placeholder", 'Example: copy or edit; JSON also works: {"action":"copy"}'),
        format: (data) => {
          const raw = data && typeof data === "object" && !Array.isArray(data) ? data : {};
          const action = normalizeMessageAction(raw.action);
          if (action) return action;
          if (Object.keys(raw).length === 0) return "";
          try {
            return JSON.stringify(raw, null, 2);
          } catch {
            return "";
          }
        },
        parse: (text) => {
          const trimmed = String(text ?? "").trim();
          if (!trimmed) return {};
          if (trimmed.startsWith("{")) {
            const parsed = JSON.parse(trimmed);
            if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
              throw new Error("data must be an object");
            }
            if (Object.prototype.hasOwnProperty.call(parsed, "action")) {
              const action2 = normalizeMessageAction(parsed.action);
              if (!action2) throw new Error("action must be copy/edit");
              return { ...parsed, action: action2 };
            }
            return parsed;
          }
          const action = normalizeMessageAction(trimmed);
          if (!action) throw new Error("action must be copy/edit");
          return { action };
        }
      }
    };
    const CUSTOM_ACTIONS = {
      poeMessageAction: async ({ shortcut }) => {
        const data = shortcut && typeof shortcut.data === "object" && !Array.isArray(shortcut.data) ? shortcut.data : {};
        const action = normalizeMessageAction(data.action) || "copy";
        return performPoeMessageAction(action);
      },
      poeSaveRename: () => {
        return saveRenameIfModalOpen();
      }
    };
    const baseShortcut = {
      url: "",
      urlMethod: "current",
      urlAdvanced: "href",
      selector: "",
      simulateKeys: "",
      icon: defaultIconURL,
      customAction: "",
      data: {}
    };
    const createShortcut = (overrides) => ({ ...baseShortcut, ...overrides });
    const defaultShortcuts = [
      createShortcut({
        name: "App-Creator",
        actionType: "url",
        url: "https://poe.com/App-Creator",
        hotkey: "CTRL+P",
        icon: APP_CREATOR_ICON
      }),
      createShortcut({
        name: "Explore",
        key: MANAGED_SHORTCUT_KEYS.explore,
        actionType: "url",
        url: "https://poe.com/explore?category=Official",
        hotkey: "CTRL+M",
        icon: "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2228%22%20height%3D%2228%22%20fill%3D%22none%22%20viewBox%3D%220%200%2024%2024%22%20style%3D%22height%3A28px%3Bwidth%3A28px%3Bdisplay%3Ablock%3Bflex%3Anone%22%3E%3Cpath%20fill%3D%22currentColor%22%20d%3D%22M12%2022C6.49%2022%202%2017.51%202%2012S6.49%202%2012%202s10%204.49%2010%2010-4.49%2010-10%2010m0-18c-4.41%200-8%203.59-8%208s3.59%208%208%208%208-3.59%208-8-3.59-8-8-8%22%3E%3C%2Fpath%3E%3Cpath%20fill%3D%22currentColor%22%20d%3D%22M8.05%2017.6c-.43%200-.84-.17-1.17-.49-.46-.47-.61-1.13-.38-1.75l1.94-5.17c.26-.78.9-1.43%201.75-1.75l5.17-1.94a1.65%201.65%200%200%201%201.75.38c.46.47.61%201.13.38%201.75l-1.94%205.17c-.26.78-.9%201.43-1.75%201.75L8.63%2017.5c-.19.07-.38.1-.58.1m7.3-8.95-4.46%201.67c-.2.08-.46.23-.57.54l-1.68%204.49%204.46-1.67c.2-.08.46-.23.57-.54z%22%3E%3C%2Fpath%3E%3Cpath%20fill%3D%22currentColor%22%20d%3D%22M12%2013.1a1.1%201.1%200%201%200%200-2.2%201.1%201.1%200%200%200%200%202.2%22%3E%3C%2Fpath%3E%3C%2Fsvg%3E"
      }),
      createShortcut({
        name: "History",
        key: MANAGED_SHORTCUT_KEYS.history,
        actionType: "url",
        url: "https://poe.com/chats",
        hotkey: "CTRL+H",
        icon: "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218%22%20height%3D%2218%22%20fill%3D%22none%22%20viewBox%3D%220%200%2024%2024%22%20style%3D%22height%3A18px%3Bwidth%3A18px%3Bdisplay%3Ablock%3Bflex%3Anone%22%3E%3Cpath%20fill%3D%22currentColor%22%20d%3D%22M7.5%2020c-.12%200-.24-.02-.35-.06-.39-.15-.65-.52-.65-.94v-3h-1C3.57%2016%202%2014.43%202%2012.5v-7C2%203.57%203.57%202%205.5%202h9C16.43%202%2018%203.57%2018%205.5v7c0%201.93-1.57%203.5-3.5%203.5h-3.05l-3.2%203.66c-.19.22-.47.34-.75.34m-2-16C4.67%204%204%204.67%204%205.5v7c0%20.83.67%201.5%201.5%201.5h2c.55%200%201%20.45%201%201v1.34l1.75-2A.98.98%200%200%201%2011%2014h3.5c.83%200%201.5-.67%201.5-1.5v-7c0-.83-.67-1.5-1.5-1.5z%22%3E%3C%2Fpath%3E%3Cpath%20fill%3D%22currentColor%22%20d%3D%22M6.75%2010.25a1.25%201.25%200%201%200%200-2.5%201.25%201.25%200%200%200%200%202.5m3.25%200a1.25%201.25%200%201%200%200-2.5%201.25%201.25%200%200%200%200%202.5m3.25%200a1.25%201.25%200%201%200%200-2.5%201.25%201.25%200%200%200%200%202.5M20%2012v6h-2c-.43%200-.79.27-.94.65l-.36-.36A1%201%200%200%200%2016%2018h-3.64l-.7.79c.31.71%201.02%201.21%201.84%201.21h2.09l1.71%201.71c.18.19.44.29.7.29.13%200%20.26-.02.38-.08.38-.15.62-.52.62-.92v-1h1c1.1%200%202-.9%202-2v-4c0-1.1-.9-2-2-2%22%3E%3C%2Fpath%3E%3C%2Fsvg%3E"
      }),
      createShortcut({
        name: "Settings",
        key: MANAGED_SHORTCUT_KEYS.settings,
        actionType: "url",
        url: "https://poe.com/settings",
        hotkey: "CTRL+SHIFT+S",
        icon: "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2228%22%20height%3D%2228%22%20fill%3D%22none%22%20viewBox%3D%220%200%2024%2024%22%20style%3D%22height%3A28px%3Bwidth%3A28px%3Bdisplay%3Ablock%3Bflex%3Anone%22%3E%3Cpath%20fill%3D%22currentColor%22%20d%3D%22M12%2015.97a3.975%203.975%200%201%201%200-7.95%203.975%203.975%200%200%201%200%207.95m0-5.94a1.97%201.97%200%201%200%200%203.941%201.97%201.97%200%200%200%200-3.941%22%3E%3C%2Fpath%3E%3Cpath%20fill%3D%22currentColor%22%20d%3D%22M12%2022.5c-.38%200-.78-.02-1.2-.08a1.56%201.56%200%200%201-1.27-1.04l-.64-1.87-1.77.87c-.54.26-1.19.2-1.66-.18-.62-.49-1.18-1.05-1.66-1.66a1.56%201.56%200%200%201-.18-1.66l.87-1.77-1.87-.64c-.56-.19-.97-.69-1.04-1.28a9.8%209.8%200%200%201%200-2.38c.07-.59.48-1.09%201.04-1.28l1.87-.64-.87-1.77c-.26-.54-.2-1.19.17-1.66.5-.61%201.06-1.17%201.67-1.66a1.56%201.56%200%200%201%201.66-.18l1.77.87.64-1.87c.19-.56.7-.97%201.28-1.04.85-.1%201.53-.1%202.38%200%20.59.07%201.1.48%201.28%201.04l.64%201.87%201.77-.87c.54-.26%201.2-.2%201.66.18.61.48%201.17%201.04%201.66%201.66.38.47.45%201.12.18%201.66l-.87%201.77%201.87.64c.56.19.97.7%201.04%201.28a9.7%209.7%200%200%201%200%202.39%201.56%201.56%200%200%201-1.04%201.27l-1.87.64.87%201.77c.27.54.2%201.2-.18%201.66q-.737.923-1.66%201.66c-.47.37-1.12.45-1.66.18l-1.77-.87-.64%201.87c-.19.56-.7.97-1.28%201.04-.41.05-.8.08-1.19.08m-.67-2.03c.44.04.9.04%201.34%200l.71-2.08a1.56%201.56%200%200%201%202.16-.9l1.97.97c.34-.3.66-.61.95-.95l-.96-1.97a1.56%201.56%200%200%201%20.89-2.16l2.08-.7q.06-.675%200-1.35l-2.08-.71a1.56%201.56%200%200%201-.9-2.16l.97-1.97c-.3-.34-.61-.66-.95-.95l-1.97.97a1.55%201.55%200%200%201-2.16-.9l-.7-2.08q-.675-.06-1.35%200l-.71%202.08a1.558%201.558%200%200%201-2.16.9l-1.97-.97c-.34.3-.66.61-.95.95l.96%201.97a1.56%201.56%200%200%201-.9%202.16l-2.07.7q-.058.675%200%201.35l2.08.71a1.56%201.56%200%200%201%20.9%202.16l-.97%201.97c.3.34.6.66.95.95l1.97-.96a1.55%201.55%200%200%201%202.16.9l.7%202.07z%22%3E%3C%2Fpath%3E%3C%2Fsvg%3E"
      }),
      createShortcut({
        name: "New Chat",
        key: MANAGED_SHORTCUT_KEYS.newChat,
        actionType: "selector",
        selector: SELECTORS.newChat,
        hotkey: "CTRL+N",
        icon: "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218%22%20height%3D%2218%22%20fill%3D%22none%22%20viewBox%3D%220%200%2024%2024%22%20style%3D%22height%3A%2018px%3B%20width%3A%2018px%3B%20display%3A%20block%3B%20flex%3A%200%200%20auto%3B%22%3E%3Cpath%20fill%3D%22currentColor%22%20d%3D%22M19.83%204.18a2.98%202.98%200%200%200-4.21%200L4.99%2014.81q-.165.165-.24.39l-1.39%204.19a.99.99%200%200%200%20.24%201.02%201.01%201.01%200%200%200%201.02.24l4.19-1.4q.225-.075.39-.24L19.83%208.39a2.98%202.98%200%200%200%200-4.21m-1.42%202.79L7.96%2017.43l-1.24.41-.55-.55.41-1.24L17.03%205.59c.38-.38%201-.38%201.38%200s.38%201%200%201.38m2.09%204.53c-.55%200-1%20.45-1%201v7h-7c-.55%200-1%20.45-1%201s.45%201%201%201h8c.55%200%201-.45%201-1v-8c0-.55-.45-1-1-1m-16%200v-7h7c.55%200%201-.45%201-1s-.45-1-1-1h-8c-.55%200-1%20.45-1%201v8c0%20.55.45%201%201%201s1-.45%201-1%22%3E%3C%2Fpath%3E%3C%2Fsvg%3E"
      }),
      createShortcut({
        name: "侧边栏切换",
        key: MANAGED_SHORTCUT_KEYS.sidebarToggle,
        actionType: "selector",
        selector: SELECTORS.sidebarToggleIcon,
        hotkey: "CTRL+B",
        icon: "data:image/svg+xml,%3Csvg%20viewBox%3D%220%200%2024%2024%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20class%3D%22ToggleSidebarCollapseButton_hamburgerIcon__VuiyV%22%3E%3Cpath%20d%3D%22M4.5%206.5h15a1%201%200%201%200%200-2h-15a1%201%200%200%200%200%202ZM19.5%2017.5h-15a1%201%200%201%200%200%202h15a1%201%200%201%200%200-2ZM19.5%2011h-15a1%201%200%200%200%200%202h15a1%201%200%201%200%200-2Z%22%3E%3C%2Fpath%3E%3C%2Fsvg%3E"
      }),
      createShortcut({
        name: "重试",
        key: MANAGED_SHORTCUT_KEYS.retry,
        actionType: "selector",
        selector: SELECTORS.retryButton,
        hotkey: "CTRL+R",
        icon: "data:image/svg+xml,%3Csvg%20viewBox%3D%220%200%2024%2024%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cpath%20d%3D%22M22.33%209.92a.973.973%200%200%200-.71-.29%201%201%200%200%200-.71.3l-.99%201.01a8.746%208.746%200%200%200-8.68-7.7C6.42%203.25%202.5%207.17%202.5%2012s3.92%208.75%208.75%208.75c2.34%200%204.53-.91%206.19-2.56a.99.99%200%200%200%20.29-.71.99.99%200%200%200-1-1c-.27%200-.52.1-.71.29a6.736%206.736%200%200%201-4.77%201.98c-3.72%200-6.75-3.03-6.75-6.75s3.03-6.75%206.75-6.75c3.35%200%206.15%202.46%206.66%205.7l-1.05-1.02c-.39-.38-1.03-.38-1.42.02-.38.39-.37%201.03.02%201.41l2.79%202.71c.38.37%201.04.36%201.41-.02l2.68-2.73a.99.99%200%200%200%20.29-.71c0-.25-.1-.5-.3-.69Z%22%3E%3C%2Fpath%3E%3C%2Fsvg%3E"
      }),
      createShortcut({
        name: "保存重命名",
        key: MANAGED_SHORTCUT_KEYS.saveRename,
        actionType: "custom",
        customAction: "poeSaveRename",
        hotkey: "CMD+ENTER",
        icon: "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2224%22%20height%3D%2224%22%20viewBox%3D%220%200%2024%2024%22%3E%3Cstyle%3E.st-theme-fill%7Bfill%3A%23111827%3B%7D%40media%20(prefers-color-scheme%3A%20dark)%7B.st-theme-fill%7Bfill%3A%23F8FAFC%3B%7D%7D%3C%2Fstyle%3E%3Cpath%20d%3D%22M9%2016.17L5.53%2012.7a.996.996%200%200%200-1.41%200a.996.996%200%200%200%200%201.41l4.18%204.18c.39.39%201.02.39%201.41%200L20.29%207.71a.996.996%200%200%200%200-1.41a.996.996%200%200%200-1.41%200L9%2016.17z%22%20class%3D%22st-theme-fill%22%2F%3E%3C%2Fsvg%3E"
      }),
      createShortcut({
        name: "复制消息",
        key: MANAGED_SHORTCUT_KEYS.copyMessage,
        actionType: "custom",
        customAction: "poeMessageAction",
        hotkey: "CTRL+C",
        data: { action: "copy" },
        icon: "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2224%22%20height%3D%2224%22%20fill%3D%22none%22%20viewBox%3D%220%200%2024%2024%22%20style%3D%22height%3A%2024px%3B%20width%3A%2024px%3B%20display%3A%20block%3B%20flex%3A%200%200%20auto%3B%22%3E%3Cpath%20fill%3D%22currentColor%22%20d%3D%22m21.205%207.556-5.291-5.265A1%201%200%200%200%2015.209%202h-6.5a1%201%200%200%200-1%201v2.235h2V4h4.503v4.265a1%201%200%200%200%201%201H19.5v5.5h-1.209v2H20.5a1%201%200%200%200%201-1v-7.5a1%201%200%200%200-.295-.709m-4.993-2.147%201.865%201.856h-1.865z%22%3E%3C%2Fpath%3E%3Cpath%20fill%3D%22currentColor%22%20d%3D%22m15.996%2012.791-5.291-5.265A1%201%200%200%200%2010%207.235H3.5a1%201%200%200%200-1%201V21a1%201%200%200%200%201%201h11.791a1%201%200%200%200%201-1v-7.5a1%201%200%200%200-.295-.709m-4.993-2.147%201.865%201.856h-1.865zM4.5%2020V9.235h4.503V13.5a1%201%200%200%200%201%201h4.288V20z%22%3E%3C%2Fpath%3E%3C%2Fsvg%3E"
      }),
      createShortcut({
        name: "编辑消息",
        key: MANAGED_SHORTCUT_KEYS.editMessage,
        actionType: "custom",
        customAction: "poeMessageAction",
        hotkey: "CTRL+D",
        data: { action: "edit" },
        icon: "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2224%22%20height%3D%2224%22%20fill%3D%22none%22%20viewBox%3D%220%200%2024%2024%22%20style%3D%22height%3A%2024px%3B%20width%3A%2024px%3B%20display%3A%20block%3B%20flex%3A%200%200%20auto%3B%22%3E%3Cpath%20fill%3D%22currentColor%22%20fill-rule%3D%22evenodd%22%20d%3D%22M19.28%204.72a3%203%200%200%200-4.24%200l-9.9%209.9q-.165.165-.24.39l-1.41%204.25a.99.99%200%200%200%20.24%201.02c.19.19.45.29.71.29.11%200%20.21-.02.32-.05L9%2019.1q.225-.075.39-.24l9.9-9.9a3.01%203.01%200%200%200-.01-4.24m-1.42%202.83-9.73%209.73-1.42.47-.47-.47.47-1.42%209.73-9.73c.39-.39%201.03-.39%201.42%200%20.39.4.39%201.03%200%201.42%22%20clip-rule%3D%22evenodd%22%3E%3C%2Fpath%3E%3C%2Fsvg%3E"
      })
    ];
    const MANAGED_ACTION_ICON_MAP = Object.freeze(defaultShortcuts.reduce((map, shortcut) => {
      if (!shortcut || typeof shortcut !== "object") return map;
      const key = String(shortcut.key || "").trim();
      const icon = String(shortcut.icon || "").trim();
      if (!MANAGED_SHORTCUT_KEY_SET.has(key) || !icon) return map;
      map[key] = icon;
      return map;
    }, {}));
    const MANAGED_ACTION_ICON_SET = new Set(Object.values(MANAGED_ACTION_ICON_MAP));
    function getManagedActionIconMap() {
      return MANAGED_ACTION_ICON_MAP;
    }
    function syncManagedActionIcons(engineInstance2) {
      if (!engineInstance2 || typeof engineInstance2.getShortcuts !== "function" || typeof engineInstance2.setShortcuts !== "function") {
        return;
      }
      const shortcuts = engineInstance2.getShortcuts();
      if (!Array.isArray(shortcuts) || shortcuts.length === 0) return;
      const nextIconMap = getManagedActionIconMap();
      let changed = false;
      const patched = shortcuts.map((item) => {
        if (!item || typeof item !== "object") return item;
        const shortcutKey = String(item.key || "").trim();
        if (!shortcutKey) return item;
        const targetIcon = nextIconMap[shortcutKey];
        if (!targetIcon) return item;
        const currentIcon = typeof item.icon === "string" ? item.icon : "";
        const shouldPatch = !currentIcon || /currentColor/i.test(currentIcon) || MANAGED_ACTION_ICON_SET.has(currentIcon);
        if (!shouldPatch || currentIcon === targetIcon) return item;
        changed = true;
        return { ...item, icon: targetIcon };
      });
      if (changed) {
        engineInstance2.setShortcuts(patched);
      }
    }
    const engine = ShortcutTemplate.createShortcutEngine({
      menuCommandLabel: "Poe - 设置快捷键",
      panelTitle: "Poe - 自定义快捷键",
      storageKeys: {
        shortcuts: SHORTCUTS_STORAGE_KEY,
        iconCachePrefix: ICON_CACHE_PREFIX,
        userIcons: USER_ICONS_STORAGE_KEY,
        iconThemeAdapted: ICON_THEME_ADAPTED_STORAGE_KEY
      },
      iconThemeAdapt: {
        enabled: true,
        lightFillColor: "#111827",
        darkFillColor: "#F8FAFC"
      },
      ui: {
        idPrefix: "poe"
      },
      i18n: {
        messages: SITE_MESSAGES
      },
      defaultIconURL,
      iconLibrary: defaultIcons,
      protectedIconUrls,
      defaultShortcuts,
      customActions: CUSTOM_ACTIONS,
      customActionDataAdapters: CUSTOM_ACTION_DATA_ADAPTERS,
      actionHandlers: {
        selector: ({ shortcut }) => {
          const selector = typeof shortcut?.selector === "string" ? shortcut.selector.trim() : "";
          if (!selector) {
            console.warn(`${logTag} selector action has empty selector:`, shortcut?.name || "(unnamed)");
            return false;
          }
          return clickElementEnhanced(selector);
        }
      },
      allowOverrideBuiltinActions: true,
      actionTypeMeta: {
        selector: {
          label: "Element click",
          shortLabel: "Click",
          color: "#FF9800",
          builtin: true
        }
      },
      colors: {
        primary: "#5D5CDE"
      },
      consoleTag: logTag,
      shouldBypassIconCache: (url) => {
        const value = String(url || "");
        return value.startsWith("https://poe.com/") || value.startsWith("https://psc2.cf2.poecdn.net/") || value.startsWith("https://qph.cf2.poecdn.net/");
      }
    });
    engineInstance = engine;
    engine.init();
    syncManagedActionIcons(engine);
    setupKeepSidebarVisible();
    registerSidebarVisibilityMenuCommand();
  })();
})();
